### ISSUE TITLE
Decoding http/quasimodo solver solution is not lossless

### ISSUE THREAD

**Issue by marcovc** [gnosis/gp-v2-services#1001]
It seems that the json price vector sent from the solver to the driver are not being correctly parsed. 

The issue is demonstrated [here](https://github.com/gnosis/gp-v2-services/tree/showcase-decoding-bug). To see it you need to fire a local instance of the http/quasimodo solver.

This is an example of the output:

```
Received response: "
{
    [...]
    "prices": {      
        "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48": "298499748615533649921417236"
    [...]
}
"

Prices: {
   [...]
    0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48: Price(
        298499748615533640000000000.0,
    ),
   [...]
}
```

The precision lost is sometimes enough to fail simulations, and perhaps explains the high simulation failure rate of the http solvers.

**Comment by vkgnosis** [comment]
I believe this is a problem with f64 precision. We either have to parse prices as Rational or U256. Since prices in the settlement on chain are always integers U256 is probably the right approach.

**Comment by vkgnosis** [comment]
@marcovc Do you know if the solver ever returns fractional numbers for these prices? If yes we have to add a little bit of extra code to remove the fractional part. If not we can use the default U256::from_str.

**Comment by marcovc** [comment]
Prices will always be integers. Same for all amounts (I'm not sure they're being used though).
