### ISSUE TITLE
Solver run with "dry-run" mode

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#1009]
It would useful to be able to run the solver in a "dry-run" mode for debugging where it does everything up to the point of submitting a transaction to the blockchain but doesn't.

We should be able to reuse the "submission strategy" abstraction to do this without modifying the code too much.

**Comment by fleupold** [comment]
This could be useful to run as a shadow simulator of prod traffic in staging!

**Comment by marcovc** [comment]
@nlordell It could use this feature for better testing solvers. Would it be enough if I just add a "dry-run" condition [here](https://github.com/gnosis/gp-v2-services/blob/49aecb7ec61794b50062f1d7c6593b6d7840a4ca/solver/src/driver.rs#L474) ?

**Comment by nlordell** [comment]
I implemented it as a "transaction submission strategy" that you can choose instead of `PublicMempool` or `ArcherNetwork`.
