### ISSUE TITLE
Don't panic if single baseline source cannot be initialized

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-v2-services#1035]
We ran into a crash-loop on Rinkeby staging this week, because the GraphQL query failed and therefore this `expect` was hit: https://github.com/gnosis/oba-services/blob/15c35b47d55c33378a03cf7c3c5b00dd901a4540/solver/src/main.rs#L319

While we should alert and react in this case, we don't want our solver or api to enter into a crash loop if it could continue to function just with other baseline liquidity.

**Comment by nlordell** [comment]
I would argue that it was OK. If this were to happen in production, then the simple solution would have been to disable the `BalancerV2` liquidity in the configuration in `values-*.yaml`, thus preventing the crash-loop from happening.

**Comment by fleupold** [comment]
My worry is that if this happens during the night, we would risk a long downtime while simply ignoring balancer sources would be a degraded but not terrible experience. 

There should be an alert but it shouldn't stop other solvers from working. As we start depending on more baselines sources the risk may become higher while the reduction in QoS would become less (for a single source).

**Comment by nlordell** [comment]
> My worry is that if this happens during the night

That's a good point, I'm convinced.

It would be nice for a "solver is operating with reduced liquidity" alert to repeat. Also something for an eventual status page (an idea I'm still very fond of).
