### ISSUE TITLE
Approximate EIP 1559 Gas price estimation

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-v2-services#1036]
@koeppelmann suggested to build another gas price estimation source that approximates EIP-1559 optimised gas pricing. It would use either [`eth_feeHistory`](https://github.com/zsfelfoldi/feehistory) or `eth_getBlockBy*` to query the current `baseFeePerGas ` and then add a fixed miner tip (e.g. 10 gwei) to that value.

Given we already re-request gas fees quite frequently (~ every 15s) we would be able to react to rising base fees. Falling base fees would still add in increased miner revenue since we are not capping the tip (this would require a proper EIP1559 implementation).

If `eth_feeHistory` is used, we could even see if the baseFee is currently rising or falling and adjust our gasPrice with that prediction (multiplying or dividing by 1.125).

An overview of EIP-1559 JSON RPC Changes can be found here: https://hackmd.io/@timbeiko/1559-json-rpc

**Comment by nlordell** [comment]
An additional thought, we can query the fee history to get the current base fee on every block as part of the "service maintenance" that we already run whenever we observe a new block.

**Comment by vkgnosis** [comment]
I agree with this. Should save us fees and also make us not pay extreme amounts when gas price through gas now spikes as we would wait for the base fee to react. If we don't get our transactions included for a short amount of time in these extreme situations that's fine and maybe even preferable.

**Comment by nlordell** [comment]
For reference, we could create a new base fee component that implements [`Maintaining` trait](https://github.com/gnosis/gp-v2-services/blob/main/shared/src/maintenance.rs) and then gets registered to update on every block:
https://github.com/gnosis/gp-v2-services/blob/2d9aa1eb318f5168c8669c61caf816b28a50377b/orderbook/src/main.rs#L345-L352

**Comment by nlordell** [comment]
I would start with BlockNative gas price estimates, which should be good enough for now. This would only be needed for EIP-1559 networks not supported by BlockNative.

**Comment by vkgnosis** [comment]
This has become more important now that GasNow has announced they will shut down on October 15th. We will probably have the blocknative estimator at that point but it would be nice to not be reliant on an external service.

**Comment by sunce86** [comment]
Do we want this to be open source? (it could become really smart estimator over time)

**Comment by nlordell** [comment]
> Do we want this to be open source?

Yes.

**Comment by nlordell** [comment]
AFAIU this has been implemented! 🎉
