### ISSUE TITLE
Keep simulating tx after submission & cancel if no longer executable

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-v2-services#1055]
We are spending about 10% of our total gas usage on failed transactions. Failing transactions use gas up until the point that they fail. If a settlement has e.g. 5 interactions and only reverts in the last one we still pay a lot of amount of gas (cf. https://etherscan.io/tx/0x5741f69b78efce3f62764a2687653624fad3505aa917fd8370c635ab6a0f35a1).

We could save money if instead of letting the tx fail, we replaced it with a 0x noop transaction at a significantly higher gas price. This requires keeping simulation running while waiting for confirmation (similar to how we keep estimating gas).

A code pointer to the submission logic: https://github.com/gnosis/oba-services/blob/73cbfa407827a1b5a2c5e81481f219c77cc9062a/solver/src/settlement_submission/public_mempool.rs#L17

**Comment by sunce86** [comment]
Done with the settlement submission refactor.
