### ISSUE TITLE
Balancer pools not considered when filtering orders with fee connection for AMMs

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#1071]
We currently filter out orders that don't have a fee connection when passing the orderbook to the solver. However, this **only** considers fee connections with Uniswap-like AMMs, and ignores Balancer weighted pools.

While this is currently not an issue (since we don't accept orders without fee connections and the orderbook API only considers Uniswap pools) this will become a problem when we add Balancer pools to the price estimates in the orderbook API, where certain orders will not be sent to the optimization solvers if they trade tokens for which there is no UniswapV2-like liquidity.

Relevant lines: https://github.com/gnosis/gp-v2-services/blob/da836b43575c6780ad750d9e114c1ab17b59e31c/solver/src/solver/http_solver.rs#L474-L480

**Comment by bh2smith** [comment]
Good catch, we should probably also link this to #1075
