### ISSUE TITLE
Integrate mStable as a liquidity source

### ISSUE THREAD

**Issue by cmagan** [gnosis/gp-v2-services#1076]
Would love to know what information is needed for this. Then I can check with mStable and add to this issue

**Comment by nlordell** [comment]
As a first step, we would need a way to get all their pools for a given token pair. Ether:
- Subgraph
- `eth_call` based on-chain reading.

Then, if we want to just pass it to the optimization solver, it shouldn't be too much work. It would be more complicated to integrate it with our baseline solver though.
