### ISSUE TITLE
Use Baseline price estimation as fallback?

### ISSUE THREAD

**Issue by vkgnosis** [gnosis/gp-v2-services#1139]
Like the gas estimators we might want to use the baseline as a fallback when Paraswap returns an error. On the other hand that could make price and gas estimates fluctuate a lot depending on whether Paraswap works or not for tokens we are bad at estimating.

**Comment by nlordell** [comment]
We definitely want this, before moving the ParaSwap price estimates to prod, otherwise ParaSwap being down would also bring down our orderbook service (in that no one would be able to place orders).
