### ISSUE TITLE
Pass balancer stable pools "scaling_rates" parameter to http solvers.

### ISSUE THREAD

**Issue by marcovc** [gnosis/gp-v2-services#1153]
Curve-like pools have the concept of "scaling_rates" (the `_xp()` method [here](https://github.com/curvefi/curve-contract/blob/master/contracts/pools/3pool/StableSwap3Pool.vy#L177-L181)). 

By default this is a dictionary with a key for each token. The value for each token is a function of a misterious LENDING_PRECISION, and by default is 10^nr_decimals of the token.

Recently we did a [PR](https://github.com/gnosis/gp-v2-solver-lib/pull/28) that adds the "scaling_rates" dictionary as an optional part of the input json for these pools. If it is not present, then it defaults to the 10^nr_decimals for each token. I haven't checked if that is a sensible default for every pool, so it would be better if instead the driver could read this dictionary from the smartcontract and pass it to the solver via the "scaling_rates" parameter.

cc/ @nlordell

**Comment by nlordell** [comment]
> The value for each token is a function of a misterious LENDING_PRECISION, and by default is 10^nr_decimals of the token.

Upon further investigation, it seems to be related to curve pools that keep balances in c-tokens on lending protocols (such as Compound and Aave) where the exchange rate (and therefore, the effective conversion of amounts to their "scaled" values) is dynamic per block.
