### ISSUE TITLE
Rebroadcast Settlement Transaction in retry logic

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-v2-services#1180]
We have repeatedly seen issues with nodes broadcasting our settlement tx correctly (both with OE as well as with Infura lately).

We should consider re-transmitting our tx as part of our retry logic. If the transaction had been broadcasted before, this will lead to an error which we can detect and ignore.

Alternatively we could connect to multiple full nodes to maximise our chances of being broadcasted.

**Comment by sunce86** [comment]
Not relevant after the settlement submission refactor.
