### ISSUE TITLE
Lower Bound Gas Price to 1 GWEI

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-v2-services#1198]
It looks like we sometimes submit 0 gas price transactions on xDAI:

![image](https://user-images.githubusercontent.com/1200333/136055253-81638083-86ca-40a9-a037-f0d26b36e165.png)

A simple fix would be to hardcode a lower bound for the gas price (e.g. 1GWEI) that we never go below regardless of what the estimator says.

Another fix could be to use the blockscout specific gas estimation service (https://www.xdaichain.com/for-developers/developer-resources/gas-price-oracle) however that seems to have a similar logic as the default OE implementation (look at the last k blocks and choose the p-th percentile).

**Comment by nlordell** [comment]
This can be closed now that we use EIP-1559 gas estimate (since we should never encounter a 0 base fee).

Where this still _might_ be a problem is that we may quote really bad priority fees. I think we can re-open this issue if we encounter that.
