### ISSUE TITLE
Make gas limit for simulation configurable

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#1227]
Right now we hard code the settlement simulation limit to the gas block limit. We probably don't want settlements that take a whole block and should make this configurable.

This has the added bonus of capping settlements to a maximum gas limit.

**Comment by sunce86** [comment]
I think this is fixed with https://github.com/gnosis/gp-v2-services/commit/ff115e497afdd006647731611e0dd31aad0eff9e
