### ISSUE TITLE
Include GP gas overhead in price estimation?

### ISSUE THREAD

**Issue by vkgnosis** [gnosis/gp-v2-services#1325]
It depends on what we want the gas amount returned by price estimation to mean. It could mean the gas this settlement would take if executed yourself outside of GP or it could mean the gas GP will likely use. The latter is more difficult to estimate because it depends on how many trades we can perform in one settlement and whether a COW happens.
This is relevant for our fee estimates and eventually positive objective value. If we estimate too low then a real settlement using more gas can end up at negative objective value. It would be better to estimate true GP gas cost and make sure the subsidy factor is set appropriately.

**Comment by fleupold** [comment]
Related to this we discussed previously that the subsidy should maybe be a fixed ETH amount (rather than a factor). This way we can say we fully subsidise the GP overhead up to a certain gas price regardless of trade size.
