### ISSUE TITLE
Balancer pool missing as available liquidity?

### ISSUE THREAD

**Issue by marcovc** [gnosis/gp-v2-services#1327]
From [this thread](https://gnosisinc.slack.com/archives/CS6NV17HP/p1635589308009200), it seems that a winning settlement by 1inch used a 80-20 balancer pool that isn't available as a liquidity source in the instance file sent to quasimodo (there no binary balancer pools involving AAVE in the instance file, in attachment below).

[instance_work.zip](https://github.com/gnosis/gp-v2-services/files/7448500/instance_work.zip)

**Comment by vkgnosis** [comment]
cc @bh2smith as balancer expert

**Comment by bh2smith** [comment]
There are four weighted pools in the instance file containing AAVE token and this is all the existing balancer v2 pools for this token. The only 80-20 AAVE-WETH pool exists on v1 as a smart pool and this is the pool that was used by 1inch. Here are some screenshots

The only 4 Balancer v2 pools containing AAVE
<img width="1530" alt="Screenshot 2021-10-31 at 1 58 07 PM" src="https://user-images.githubusercontent.com/11778116/139585121-343ad1d8-e946-4721-8108-d2c18081f06b.png">


The Trade we are investigating from 1inch that went through the v1 Pool - found [here](https://pools.balancer.exchange/#/pool/0xc697051d1c6296c24ae3bcef39aca743861d9a81/swaps)
<img width="1283" alt="Screenshot 2021-10-31 at 2 10 40 PM" src="https://user-images.githubusercontent.com/11778116/139585133-6497d6f5-ee27-4104-a91e-a02951efb4fa.png">
