### ISSUE TITLE
Shadow-solver is causing a lot of quasimodo traffic

### ISSUE THREAD

**Issue by josojo** [gnosis/gp-v2-services#1338]
The solver quasimodo was called 429 times in the last hour by the shadow solver:
https://logs.gnosisdev.com/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-60m,to:now))&_a=(columns:!(_source),filters:!(),index:de1f5360-a9ae-11ea-acbb-9d2e3cb124ca,interval:auto,query:(language:kuery,query:'log:%22solver%20Quasimodo%20found%20solution%22%20AND%20kubernetes.pod_name:%20%22dev-dfusion-v2-solver-shadow%22'),sort:!())

This consumes quite some resources and sometimes prevents normal request to be filled.

I think we should change the logic that the shadow-solver also just tries to solve the batches every 30 secs.

**Comment by vkgnosis** [comment]
Makes sense to me. I recently removed the driver single run interval parameter which allowed you to change how long it should sleep between runs. After adding it back it would be fast to fix by increasing the value.

**Comment by nlordell** [comment]
Should be fixed sith #1367
