### ISSUE TITLE
Add flashbots protect API

### ISSUE THREAD

**Issue by sunce86** [gnosis/gp-v2-services#1342]
In order to use flashbots protect API, custom implementation for cancelling logic needs to be added.

Plan is to create a new transaction strategy for flashbots as a clone of archer strategy, and reimplement tx submit and cancelling functions.

From there, further refactor of transaction submission logic can be made for all strategies, in order to extract common code.

**Comment by nlordell** [comment]
I think at first we can implement the "general" submission logic (i.e. making sure that the settlement simulation still passes on new blocks) and then add Flashbots specific support if needed.

Note that we already have Archer (now called Eden) support (which had some custom cancellation and submission logic).

**Comment by vkgnosis** [comment]
I talked about this with Dusan. I felt that we wanted Flashbots quickly so it would be better by starting out with a copy paste of the Archer logic. Then refactoring later to see what components can be merged and refactoring the existing standard node strategy.

**Comment by nlordell** [comment]
OK, sounds fair. I would have done this in "reverse" by moving the simulation of settlements on new blocks to the `CustomNodes` strategy (so that we support all private transaction RPC endpoints in a limited capacity - like TaiChi) and then added custom Flashbots RPC support if needed.

**Comment by gakonst** [comment]
FYI if you ever end up switching to ethers-rs, there's a Flashbots plugin for it https://github.com/onbjerg/ethers-flashbots

**Comment by sunce86** [comment]
Implemented.
