### ISSUE TITLE
Price estimations take a long time

### ISSUE THREAD

**Issue by josojo** [gnosis/gp-v2-services#1359]
Marco [highlighted](https://gnosisinc.slack.com/archives/C020UHS2UEL/p1636228074017700) that many instances have little time to left.

I think it is due to the fact that price estimations quite often take a long time. If one looks through the logs:
https://logs.gnosisdev.com/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(_source),filters:!(),index:de1f5360-a9ae-11ea-acbb-9d2e3cb124ca,interval:auto,query:(language:kuery,query:'log:%22estimate_prices%20took%22'),sort:!())
one sees many instances with >=5 secs.

Here is one example, where there was little time to solve the instance: 
https://logs.gnosisdev.com/app/kibana#/discover/doc/de1f5360-a9ae-11ea-acbb-9d2e3cb124ca/logstash-2021.10.18?id=apyrlHwBGsivd2V8bgsx

and just before the price estimation took 11 secs:
https://logs.gnosisdev.com/app/kibana#/discover/doc/de1f5360-a9ae-11ea-acbb-9d2e3cb124ca/logstash-2021.10.18?id=dQarlHwBIBf7G29ggfyG

**Comment by nlordell** [comment]
Looking into this a bit, it looks like some of the batched `eth_call` requests are taking a long time. This one took 3 seconds for example: https://logs.gnosisdev.com/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-18T18:00:00.000Z',to:'2021-10-18T19:00:00.000Z'))&_a=(columns:!(_source),filters:!(),index:de1f5360-a9ae-11ea-acbb-9d2e3cb124ca,interval:auto,query:(language:kuery,query:'log:%22102854%22'),sort:!())

**Comment by nlordell** [comment]
I would also expect `eth_calls` to be cached (they are retrieving Uniswap pool data here for example) but they appear not to be.

**Comment by vkgnosis** [comment]
I would expect the same since #1137 .

**Comment by vkgnosis** [comment]
Since #1137 we should fetch all pools in one go. I'm not sure about why they're not cached. The baseline price estimator is indicating it is OK with "recent' results for the pools.

**Comment by vkgnosis** [comment]
It is expected that there are some uncached pools btw for the http solver. Because it needs more price estimates than the driver.

**Comment by marcovc** [comment]
This keeps happening (see [this post](https://gnosisinc.slack.com/archives/C022S0FM1GW/p1636642414014100)).

Since price estimation seems to be the culprit, one solution could be to use the price estimation algorithm we use in the solver, which takes less than a sec and has been robust so far.
