### ISSUE TITLE
Reintroduce persistent local contracts deployment loaded at runtime

### ISSUE THREAD

**Issue by vkgnosis** [gnosis/gp-v2-services#1377]
See https://github.com/gnosis/gp-v2-services/pull/1371 .

**Comment by nlordell** [comment]
Do you think it maybe makes sense to have:
```
struct Contracts {
   // all deployed contracts
}
```

**Comment by vkgnosis** [comment]
Yes. See #1379 above.That fact that I would have broken staging with the other PR is a little scary so now I'm thinking I should do that issue first.
