### ISSUE TITLE
[Cowswap] API Price Strategy check endpoint

### ISSUE THREAD

**Issue by W3stside** [gnosis/gp-v2-services#1396]
Hi guys - as we mentioned briefly some weeks back, would be great to have an endpoint returning the best price strategy for querying prices. Something we could use below that returns which endpoint to use: `COWSWAP` or `LEGACY` (names can be whatever)
![image](https://user-images.githubusercontent.com/21335563/141976737-1abfe973-4930-4664-909f-ba2afcf3c189.png)

where we can check and in case of a change, fallback and continue offering service to the frontend:
![image](https://user-images.githubusercontent.com/21335563/141977100-d2d40dbb-d21e-4609-9e14-6e89a672cd19.png)

**Comment by W3stside** [comment]
@fleupold moved here

**Comment by nlordell** [comment]
Discussing our options on Slack. Either:
- Host static file on Github
- Host static file on our Nginx ingress

**Comment by nlordell** [comment]
Closing since, AFAICT, this will be configured with our Github configuration.

**Comment by fleupold** [comment]
This would have come in handy today.

**Comment by nlordell** [comment]
AFAIK this was implemented in [v1.8.0](https://github.com/gnosis/cowswap/releases/tag/v1.8.0). Specifically: https://github.com/gnosis/cowswap/pull/1835
