### ISSUE TITLE
Support non-uniswap pools for quasimodo price estimator

### ISSUE THREAD

**Issue by taminomara** [gnosis/gp-v2-services#1412]
Right now we only consider uniswap v2 pools for quasimodo price estimator. This happened because we use different representations for liquidity in the `orderbook` and `solver` crates, so supporting other pools is somewhat difficult. Once pool representations are unified, we can support all of them. Alternatively, we can try to add support for paraswap before that happens.

**Comment by nlordell** [comment]
:100:
