### ISSUE TITLE
Price estimators refactor

### ISSUE THREAD

**Issue by taminomara** [gnosis/gp-v2-services#1414]
Price estimators share a lot of common code, and do a lot of duplicate work. I propose to avoid this by switching to the following scheme:

- individual price estimators become private,
- they are accessed via the `PriceEstimator` facade,
- `PriceEstimator` pre-calculates commonly used values, performs necessary checks, and calls estimator implementations,
- `PriceEstimator` is mockable.

**Comment by nlordell** [comment]
I think this is a good idea.

This would allow us to do all the common checks (for example "bad token detection") in a common place. Also, once we move to "baseline trade simulation" we would only have to include this in one place.

**Comment by MartinquaXD** [comment]
Some refactoring already happened in #1499 . Just mentioning it for traceability.

**Comment by nlordell** [comment]
I think it is OK to close this as this is the purpose of the current `SanitizedPriceEstimator` component.
