### ISSUE TITLE
BUG: Driver passing native ETH token with null decimals to Quasimodo solver

### ISSUE THREAD

**Issue by bh2smith** [gnosis/gp-v2-services#1495]
Reported by @marcovc who can provide instance details, but currently in production this is happening.

We need to find the PR that introduced passing raw orders (i.e. without mapping ETH to WETH) into the solvers.

**Comment by nlordell** [comment]
AFAICT this appears to be unique to the price estimator and not the actual solver.

**Comment by bh2smith** [comment]
We have not been able to reproduce the error log you shared 

```
2021-12-20T09:29:51.048Z  WARN shared::price_estimation::competition: price estimation error estimator_name=Baseline query=Query { sell_token: 0x6810e776880c02933d47db1b9fc05908e5386b96, buy_token: 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee, in_amount: 907485758299467968, kind: Sell } err=NoLiquidity
```

and as far as we can tell the baseline price estimator does accurately find available liquidity for both buy and sell orders with ETH as the buy token.

We have put together a PR addressing the initial  issue of sending accurate native token details off to the Quasimodo price estimator that @MartinquaXD will push soon. This may also require some coordination with @marcovc on the solver side.
