### ISSUE TITLE
SolvableOrderCache may deadlock

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-v2-services#1505]
We have seen some alerts of the form

> 2021-12-28T12:10:19.054Z ERROR solver::driver: single run errored: get_orders
Caused by:
   0: error sending request for url (http://.../api/v2/solvable_orders): error trying to connect: tcp connect error: Connection refused (os error 111)
   1: error trying to connect: tcp connect error: Connection refused (os error 111)

Which come from our API pod not being ready. Our readiness check tests if we can fetch the list of solvable orders, which seemingly we couldn't at the time (I tested it manually and got a 503)

The logs show no entries in this timeframe (normally there is a "updated solvable orders" message every few seconds): https://logs.gnosisdev.com/goto/12fb4a80-67db-11ec-b0ab-3756576dadd4.

This leads me to believe that there was some form of deadlock on the solvable orders cache preventing it from being updated and preventing people from querying the list of solvable orders.

I noticed that we use a `std` Mutex in this component which [can be dangerous](https://docs.rs/tokio/1.12.0/tokio/sync/struct.Mutex.html#which-kind-of-mutex-should-you-use) in combination with tokio. However, I can't see how we might be holding it across awaits, so I'm not sure it is related. The issue also seems to only be happening very sporadically. It does however, lead to ~5 minute downtime.

**Comment by fleupold** [comment]
> In this case we do not update the solvable orders as they cannot have changed. 

We should in this case still be able to query solvable_orders though. I created this task in reaction to seeing 503 alerts from our pod (an availability metric that I think we should try to minimise)

**Comment by fleupold** [comment]
Closing this issue as it seems like the upshot of there being a deadlock is not correct.

**Comment by vkgnosis** [comment]
I think there might have been a deadlock like I say in the last paragraph. But not sure if it was in solvable_orders.
