### ISSUE TITLE
Uniswap V2 Gas Cost Seems Low

### ISSUE THREAD

**Issue by bh2smith** [gnosis/gp-v2-services#1526]
We have hard coded 60K gas for uniswap swap here, but other [sources](https://crypto.com/defi/dashboard/gas-fees) are suggesting the cost is around 137K  (158 - 21).

https://github.com/gnosis/gp-v2-services/blob/397043bb1d4bf2cdf3a59dc94c7ecae2309097c8/crates/shared/src/sources/uniswap_v2/pool_fetching.rs#L13

[Here](https://dune.xyz/queries/329939) is a dune query for Average Gas Used on Uniswap V2 over the past 7 days (waiting for results)

This line was last touched in #558

**Comment by vkgnosis** [comment]
One difference is that this constant is per hop as this is how we model uniswap liquidity. Other statistics probably model a full swap which can contain multiple hops. So some increase is expected. We're also adding a constant 50k gas in `crates/shared/src/baseline_solver.rs` .

**Comment by nlordell** [comment]
60K + 50K = 110K which is ~21K very close to the 137K average. (off by 6K).

**Comment by bh2smith** [comment]
So should we change it or close this? I don't believe we subtract the 50k overhead in balancer.

**Comment by nlordell** [comment]
Now that I think about it a bit more, we should maybe change this. While the gas costs that we have configured are accurate for a multi-hop Uniswap - we currently don't do multi-hop Uniswaps and always use the router on every hop.
