### ISSUE TITLE
Cache Price Estimation API Requests

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#1533]
We are currently being rate-limited by ParaSwap because we are making around 1000 requests per minute. It looks like we are sending a lot of duplicate requests (especially when computing the native token price for some sell token - since the amounts are always the same and it is likely that a user makes multiple price estimate requests for the same sell token while tweaking amounts).

**Comment by vkgnosis** [comment]
There are three potential places where caching could happen:

- Paraswap
- Backend
- Frontend

We can't influence Paraswap but still it is one perspective to say that they should be caching (and they probably are) so we don't have to do it for them. Still it is work to send network requests so it does make sense to have caching in the backend. It depends on how often the amounts are the same. We probably cannot answer this without actually implementing a cache and metrics.
If these requests you mention as being duplicate originate from the frontend then there could be some caching there too. But not sure from top of my head if that is the case or these are prices we request in backend logic.

**Comment by nlordell** [comment]
Specifically, I was thinking of caching ParaSwap API requests. For example, for two different FE requests:
- quote SELL 100 BAL for GNO
- quote SELL 1000 BAL for GNO

We have a the duplicate ParaSwap API to compute the sell token's ETH sell price:
- quote BUY 1ETH for BAL

In fact, the API request for getting ETH sell prices is much more likely to be a cache hit because only the sell token varies (instead of sell token, buy token and amount for usual price requests).

**Comment by fleupold** [comment]
>  It depends on how often the amounts are the same

No exact science, but I checked https://logs.gnosis.io/goto/c30951d0-6efa-11ec-9c50-a508084c3610 to see that some requests are indeed sent 2-6 times within the matter of a few seconds.

**Comment by sunce86** [comment]
> * quote SELL 100 BAL for GNO
> * quote SELL 1000 BAL for GNO

Are these REALLY the same requests or we just approximate them as being the same?
Asking because I am not sure how Paraswap works internally. These two queries should theoretically make different slippages right?

**Comment by vkgnosis** [comment]
We are not going to cache when the amounts are different. What Nick means is that for both of those requests we will make the same "quote BUY 1ETH for BAL" estimate so that one can be cached.

**Comment by nlordell** [comment]
Closing as this should be solved by #1548 and #1555
