### ISSUE TITLE
Remove code to filter out pools with 0 amounts for http solver

### ISSUE THREAD

**Issue by vkgnosis** [gnosis/gp-v2-services#1540]
This should be done once the solver version is released that internally filters them instead of erroring. Applies to quasimodo price estimator in orderbook crate and http solver in solver crate.

**Comment by nlordell** [comment]
Specifically here:

https://github.com/gnosis/gp-v2-services/blob/a7915d1529cbebf0a85a2396fc8f6e098c69f65f/crates/solver/src/solver/http_solver.rs#L342

And here:

https://github.com/gnosis/gp-v2-services/blob/3eef426abf33b4ead9c3a9c88275e2d5d061af37/crates/shared/src/http_solver_api/model.rs#L48
