### ISSUE TITLE
Decimals with null values (again)

### ISSUE THREAD

**Issue by marcovc** [gnosis/gp-v2-services#1554]
[Here](https://logs.gnosis.io/app/discover#/doc/63bc0b10-5f93-11e9-bf17-fbe383fc7c9c/logstash-2022.01.11?id=Stw7Sn4BwV0iY5ldQe5u) is an example in prod where the driver is sending a token with "null" in the decimals field. It seems it is coming from the price estimator.

Might be related with #1495 .

**Comment by vkgnosis** [comment]
From a quick glance at the code it is possible that our token info fetcher errored when talking to the node in which case it will return an empty hash map so all the token info related things would be unll.

**Comment by nlordell** [comment]
This is a Rinkeby instance and `0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48` is not a contract (so it has no `decimals`).

**Comment by nlordell** [comment]
@marcovc can this be closed? Or do you have a separate proposal on how the driver should handle these cases?

**Comment by marcovc** [comment]
Yes, we stopped requiring decimals, so please close. Thanks!
