### ISSUE TITLE
`/auction` Endpoint

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#1571]
This issue captures the work to define a new `/auction` endpoint. Specifically, we want this to depricate the `solvable_orders` endpoint and return additional information. Right now, the only additional information is the list of "external prices" that are used for computing the objective value (instead of having this be calculated by the driver).

We need to:
- [ ] Define the API in the `openapi.yaml` spec (there is an open question if we want to include liquidity or not in the auction data)
- [ ] Compute external prices in the `orderbook` service.
  - [ ] Decide where the price estimates come from (`Quasimodo` vs `Baseline`).
  - [ ] This **requires** Balancer liquidity to be considered in the `orderbook` service
- [ ] Implement the route

**Comment by vkgnosis** [comment]
We've mentioned a few times that we could phase out the baseline estimator and replace it with quasimodo everywhere. That would make a big difference here as it would obsolete making the baseline estimator handle balancer so we should probably discuss that first.

**Comment by nlordell** [comment]
Added a point to the list.

In general, I also prefer using `Quasimodo` for all estimates (since they are better quality). That being said, it would be nice to be able to start the `orderbook` without an external service. Maybe this needs to be configurable? Is it even worth it?

**Comment by vkgnosis** [comment]
Yeah that is the biggest downside, that you need the external service to run. For example when running locally or on CI. On the other hand it doesn't seem reasonable that we would support the baseline estimator forever. A way around that could be to introduce a dumb estimator that always returns a price of 1. Or hardcoded prices per preconfigured pair.

**Comment by nlordell** [comment]
> On the other hand it doesn't seem reasonable that we would support the baseline estimator forever.

I'm torn about this. On the one hand, I agree, the maintenance cost of keeping some of these legacy solvers around is non-negligeable. On the other, the Baseline solver still accounts for around 2.5% (based on Shadow-solver traffic) of solutions, so there still seems to be a tiny niche for it, and it allows the infrastructure to run without any external dependencies (like in CI or locally as you pointed out).

**Comment by fleupold** [comment]
> Decide where the price estimates come from (Quasimodo vs Baseline).

Shouldn't the price estimates use the same logic as our price estimation endpoints (in particular quote 1Inch, Paraswap, 0x)? 

Part of the potential impact of this task it to enable trading Univ3 only pools without integrating Univ3 liquidity into the baseline or Quasimodo solver (as fetching liquidity their is a big undertaking).

**Comment by nlordell** [comment]
> Shouldn't the price estimates use the same logic as our price estimation endpoints (in particular quote 1Inch, Paraswap, 0x)?

I fear that for larger batches, the time to estimate prices would be too high.

**Comment by fleupold** [comment]
> I fear that for larger batches, the time to estimate prices would be too high.

I wonder how time critical those estimations need to be? Technically, we have already priced the sell token in ETH (for the fee estimate), so with the right caching that value may be reusable. Maybe the cache (also for the buy token) can be updated asynchronously so it's not blocking the hot `/auction` fetching path.

**Comment by nlordell** [comment]
🤦 Right! We can cache these values.

> I wonder how time critical those estimations need to be? Technically, we have already priced the sell token in ETH (for the fee estimate), so with the right caching that value may be reusable.

Actually, a slightly different approach that would make computing the external prices work for all accepted orders would be to use the fee data we store in the database. It already contains the sell token to ETH price, and if we augment it with a buy token to ETH price column (which we can compute at price estimation time with the data we already fetch) then this becomes very easy.

If we compute a weighted average (based on order age) we might get some pretty good external prices without much delay.

> I wonder how time critical those estimations need to be?

This is a good question, my intuition is "high" since as if affects settlement time and makes it more likely for block chain state to change. Just an intuition though.

**Comment by vkgnosis** [comment]
For the prices that the orderbook gives we *only* need the price in eth, right? It is the job of the solvers to calculate the prices for the solution and we need the eth prices (of sell, buy token) only for the objective value. Or am I misunderstanding?
In that case those eth prices aren't critical with regards to on chain state changing making settlements fail. There would have to be huge price movement for that to matter much for the objective value. So a couple of minutes old prices seem fine but longer than that we probably want to re-estimate.

**Comment by nlordell** [comment]
> For the prices that the orderbook gives we only need the price in eth, right? It is the job of the solvers to calculate the prices for the solution and we need the eth prices (of sell, buy token) only for the objective value. Or am I misunderstanding?

Correct, we need some reference prices for objective value computation. Having prices for all auction tokens in ETH is enough here.

> There would have to be huge price movement for that to matter much for the objective value.

I think what could happen is if we have two solutions with a single trade (just as a contrived example):
1. Buy x X for a A
2. Buy y Y for a A

Then the only thing that will determine the winner, `(x - limit_x) * price_x ? (y - limit_y) * price_y`. So, inaccurate prices in X or Y may cause us to chose the wrong winner (since we can't normalize the surplus and we are basically comparing apples to oranges).

This is why I proposed using a weighted average of prices from the stored fee data in the orderbook database (weighted on the age of the order, so favoring newer fee measurements).

That being said, there still are some edge cases that are problematic with using my suggestion (for example a day old order). That being said, I like the "cleanliness" in the sense that if the order is in the orderbook, then it can be considered for trading.

> on chain state changing making settlements fail

This is more about the time between a user placing an order and it getting traded. Longer "batch preparation" times may contribute to this. (Maybe its negligible though - it was just an intuition).

**Comment by nlordell** [comment]
This has been implemented 🎉
