### ISSUE TITLE
Optimize quoting process

### ISSUE THREAD

**Issue by MartinquaXD** [gnosis/gp-v2-services#1582]
The current approach of generating a quote for an order involves estimating the order as it is as well as estimate an "artificial" order buying `WETH` for the `sell_token` of the user order.
Let's call the first order `buy_token_estimate`. This will have whatever order kind the user specified.
Let's call the second one `native_token_estimate`. This will always be a buy order.
Having at least one buy order for every user order regardless its order kind poses a problem for PriceEstimators which can't handle buy orders (e.g. `OneInchPriceEstimator`).
The [code section](https://github.com/gnosis/gp-v2-services/blob/main/crates/orderbook/src/fee.rs#L291-L334) best shows the main pain point.

Now the question is: Is there an architecture which gives us enough flexibility to actually use PriceEstimators which can't handle buy orders?
There are different solutions which different trade-offs.

### Improve Caching `native_token_estimate`
As you can see [here](https://github.com/gnosis/gp-v2-services/blob/main/crates/orderbook/src/fee.rs#L339-L386) we already [cache](https://github.com/gnosis/gp-v2-services/blob/main/crates/orderbook/src/database/fees.rs#L53-L81) previously computed `FeeData` to skip computing it again for identical orders.
When we compute the `sell_token_price` we always estimate a buy order with a constant amount where WETH is the buy_token. Only the order kind and sell_token is variable.
Given that information one option could be to add another code path which only fetches the `sell_token_price` for the user order. This should result in many cache hits where every cache hit means that a price estimator doesn't have to estimate a buy order.
I think this could be a general improvement but in the particular example of the `OneInchSolver` it could make the estimator viable at all.

### Forwarding Estimations Based on Order Kind
Given the fact that not every estimator is able to estimate every order kind, we could simply forward order estimations to different estimators based on the order kind. Where this should happen is unclear. One option could be to have 2 distinct PriceEstimator hierarchies (basically copy the one we have but with out the `OneInchPriceEstmator`). Alternatively we could introduce a `MuxPriceEstimator` which takes 2 estimators (1buy, 1sell) to construct and forwards  
queries appropriately.

### Give PriceEstimators a Fallback
This is basically a different flavor of the previous solution. Instead of deciding outside of the PriceEstimator where to forward quotes to, a ParentPriceEstimator could do that by having a fallback ChildPriceEstimator for scenarios the parent can't handle. This pattern is already widely used in the code base but not for this particular use case.
The downside is that it would result in doing some work twice. Imagine giving the `OneIncPriceEstimator` the `BaseLinePriceEstimator` as a fallback. Now the `BaseLinePriceEstimator` would estimate an order twice for every order `OneInchPriceEstimator` can't handle (once as the fallback and once as the standalone `BaseLinePriceEstimator`).

### Use Rich Price API
Computing the value of a token like we do is a common use case. That's why zeroex and paraswap have a rich price API which does just that. This approach would essentially make computing the `sell_token_price` a responsibility of the price estimator. This is not really a solution for the problem at hand, but this change is really desirable for zeroex and paraswap so a solution enabling `OneInchPriceEstimtator` shouldn't make it more difficult to implement this change for zeroex and paraswap. This could be a bigger redesign of the price estimation API. This design would probably go well with the previous idea.
One thing we should keep in mind is how we can properly utilize our existing cache for estimators which are not paraswap and zeroex. Those would have to implement the rich price API on their own while still caching as much as possible.

**Comment by vkgnosis** [comment]
One imo reasonable suggestion we already thought about is always using a "local" price estimator for the native token order. That would fix this issue too and is kind of like your fallback idea. The local estimator would be quasimodo or baseline.

**Comment by nlordell** [comment]
> One imo reasonable suggestion we already thought about is always using a "local" price estimator for the native token order

For reference, here is the issue: https://github.com/gnosis/gp-v2-services/issues/1542

**Comment by nlordell** [comment]
Some general comments:

> Improve Caching native_token_estimate
> I think this could be a general improvement but in the particular example of the OneInchSolver it could make the estimator viable at all.

While I agree, I do see using our DB cache as a little orthogonal WRT to making the 1Inch price estimates work. While it would allow estimates in many situations, it doesn't solve the problem of 1Inch price estimator not being able to compute the sell token price in ETH. If we do implement this, I still think we need something to make the 1Inch price estimator work even without a cache.

> Give PriceEstimators a Fallback

Another flavour of this is to have `MinFeeCalculator` take two price estimators, one for computing order estimates (so `sell_token` for `buy_token` price and gas estimates) and another for computing sell token ETH price estimates (so buy 1ETH with `sell_token` price).

This allows us to configure the two separately, so we can configure 1Inch price estimator is only used for the order estimate. Additionally, this also allows us to implement #1542 by configuring the sell token ETH price estimator to just use `Quasimodo` and/or `Baseline` solvers.

**Comment by nlordell** [comment]
Personally, I'm the most fan of the "rich API" approach. There are risks however (for example, we don't know where the ETH and USD prices come from in 0x, 1Inch and ParaSwap API, so it might cause us to under-quote fees for illiquid tokens).

**Comment by nlordell** [comment]
Also worth metioning is @fleupold's comment here: https://github.com/gnosis/gp-v2-services/issues/1571#issuecomment-1014766988. Specifically, this is about the `/auction` endpoint and the suggestion to use all our price estimators (0x, ParaSwap, 1Inch) for computing the "external price" array.

This might have an impact on what we chose to use for "sell token ETH price estimator" in this particular case.

**Comment by MartinquaXD** [comment]
The caching idea is indeed no solution which makes the OneInchPriceEstimator work for every scenario, but it could work around the problem enough to make it viable.
Always using `quasimodo` for the `native_token_estimate` sounds very nice from a maintenance perspective. Not sure how big the consequences for our and the users costs might be if we don't have estimator competition for the `native_token_estimate`, though.
I guess this change should be easy enough to get the `OneInchPriceEstimator` going soon while being easy to throw away once we tackle the rich price API.

**Comment by nlordell** [comment]
Just to summarize what we discussed in the meeting today:

We decided to add a new component specialized specifically for computing token prices in ETH (more specifically, native token price, so xDai on Gnosis Chain).

This component can hopefully be implemented in terms of the current `PriceEstimating` interface (and use the same underlying price estimators). Also, critically, it should be **cached** (keyed on the token we are estimating the price for) and shared with the code that computes the `/auction` external price vector. Furthermore this cache can be updated on a periodic basis (together with how we update the `solvable_orders`).

We also decided to not to do use rich API responses

**Comment by fleupold** [comment]
> We also decided to not to do use rich API responses

This means that even with the `/auction` endpoint we won't increase the number of tokens that are tradable (we have a lot of unsupported tokens because of "no pool")? Is there another plan to support those without adding more native liquidity to the system?

**Comment by MartinquaXD** [comment]
With the merge of #1615 this issue can be considered done.
