### ISSUE TITLE
Integrate real solvers

### ISSUE THREAD

**Issue by e00E** [gnosis/gp-v2-services#160]
They will be available through an http api and we will need to provide them with uniswap pool information.
TODO: add a link to the http api documentation

**Comment by fleupold** [comment]
@marcovc & @josojo can provide information on how to access the API

**Comment by e00E** [comment]
I did find https://github.com/gnosis/gp-v2-solver/pull/26 and was able to look at the api locally.

**Comment by josojo** [comment]
Yeah, exactly. This is all we have until now :)
