### ISSUE TITLE
Panics in share_common_pool_state

### ISSUE THREAD

**Issue by josojo** [gnosis/gp-v2-services#1605]
We had two panics in production:

https://gnosisinc.slack.com/archives/CUD4MUCUF/p1643404096116769
https://gnosisinc.slack.com/archives/CUD4MUCUF/p1643442554550739?thread_ts=1643404096.116769&cid=CUD4MUCUF

Maybe the author of the share_common_pool_state could look in this? 

From the comments in code, we can read:
>This method is only ever
/// meant to be used internally, so we don't have to worry that these
/// assumptions leak out of this module.

Does this assumption still holds true? What is meant with Internally?

**Comment by vkgnosis** [comment]
Since Nick is on vacation and panic could be serious I will look into this.
