### ISSUE TITLE
Update gas prices within runloop

### ISSUE THREAD

**Issue by josojo** [gnosis/gp-v2-services#1607]
We got a lot of simulations errors, due to the fact that the `GasPriceLowerThanBaseFee` happened. IN this case, we should run the simulations with higher gas prices or update the gas prices before we start simulation.

This sometimes blocks solution submission for quite some time, if gas prices are on the raise for a longer time: 
E.g. see here: https://logs.gnosis.io/goto/5485a870-81fc-11ec-917b-db25a6c668a7

**Comment by sunce86** [comment]
Current gas price estimator returned invalid values (`max_fee_per_gas < base_fee_per_gas` which must not happen):
https://logs.gnosis.io/goto/1003a540-827d-11ec-88a8-6959bbfe856a

Example: 
```
{ legacy: 0.0, eip1559: Some(GasPrice1559 { base_fee_per_gas: 245135109214.0, max_fee_per_gas: 211991655976.19406, max_priority_fee_per_gas: 1397879349.0 })
```

I'm in favor of adding a check for this in the code, and if check fails:
1. raise an error about this to the alert channel
2. add a fix setting `max_fee_per_gas = 2 * base_fee_per_gas`
