### ISSUE TITLE
Tokens with "only uni v3 liquidity" are not tradable on our exchange

### ISSUE THREAD

**Issue by josojo** [gnosis/gp-v2-services#1611]
We had a customer complaining that the[ new UST token]( https://etherscan.io/token/0xa693b19d2931d498c5b318df961919bb4aee87a5) is not supported. It

The reason is that the bad detector does not find a pool, and then concludes that it is a bad token. Though, there are uni v3 pools.
It seems like there are a lot of tokens which are traded on-chain - mostly on uni v3 - and hence are detected as bad tokens. See here for a long list of [potentially affected tokens ](https://logs.gnosis.io/goto/762be320-82b2-11ec-88a8-6959bbfe856a)
and one more [example](https://etherscan.io/token/0xa973c558265ad458031fa3067071646836df7713#tokenTrade).

Possible solutions: 
- Also check for uni v3 pools?
- Remove this criteria from the bad token detection, if other prices are available.

**Comment by vkgnosis** [comment]
Related https://github.com/gnosis/gp-v2-services/pull/1567

**Comment by vkgnosis** [comment]
Closing because this has been fixed.
