### ISSUE TITLE
New "fast" price estimate

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#1646]
Add a new parameter to the `quote` endpoint for doing a "fast" price estimate vs an "optimal" one. One possible implementation is to return the first successful price estimate. Another is to only use Baseline and Quasimodo, or time box the estimates.

This would allow the FE to make two requests: `GET /quote?startegy=fast` and `GET /quote?strategy=optimal` and then show initial prices in the UI and then update the price once it gets the best one.

**Comment by MartinquaXD** [comment]
Implemented in #1659 (#1650 is related)
