### ISSUE TITLE
Add tiered COW subsidy support

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#1686]
This issue captures the work to add "tiered" support for COW/vCOW subsidies.

Since we don't really have an idea of how many tiers or amounts for each tier, we should make it configurable like:

```
--cow-fee-factors "10.2:0.9;100.0:0.75;1000.0:0.5"
```

This would meant that:
- If your balance is greater than `10.2 COW` (or `10200000000000000000` atoms) and less than `100.0 COW` then you get an additional 0.9 factor on your trade
- If your balance is greater than `100.0 COW` but less than `1000.0 COW` then you get a 0.75 additional factor
- If your balance is greater than `1000.0 COW` then you get a 0.5 additional factor

**Comment by MartinquaXD** [comment]
This approach doesn't seem flexible enough with #1685 in mind.
@nlordell what do you think about adding a single CLI argument which wouldn't have to change once that linked issue gets tackled?
`--subsidy-config <file>` would allow us to very easily deserialize any sensible format with `serde`. This seems nicer than having to implement custom parse logic and adding new parameters every time we change how we want to calculate the subsidy.

**Comment by nlordell** [comment]
> This approach doesn't seem flexible enough with https://github.com/gnosis/gp-v2-services/issues/1685 in mind.

I think it should be fine - the buckets would be total balance (i.e. the sum of the two balances proposed in #1685)

> `--subsidy-config <file>`

Honestly, I really like this idea. In general, I would prefer this for all our configuration (not just limited to subsidy configuration). Something like a Toml file would be likely more readable and allow for rich nested configuration objects like
```toml
[[solvers]]
kind = "OneInch"
account = "0x...."

[[solvers]]
kind = "Quasimodo"
account = "0x...."
```

Instead of having two lists that we merge.

Also interesting to consider would be to take a similar approach to [`rocket`](https://rocket.rs/) and use [`figment`](https://docs.rs/figment) to merge configuration from different sources (Toml file and environment for example).

The reason we haven't done this in the past was difficulties with our Kubernetes setup, but we should reconsider!

**Comment by sunce86** [comment]
How would having a configuration file save us from having to implement custom parsing logic? Either way we have to support the change by making the changes to internal struct used for deserialization, and if there is some more complex logic like for the parameter in this issue (`--cow-fee-factors "10.2:0.9;100.0:0.75;1000.0:0.5"`), we need to support it in the custom deserializator? Or I am missing something...

**Comment by MartinquaXD** [comment]
I don't think you are missing anything. I just didn't consider changing the internal struct which the config file should get deserialized to as maintaining custom logic. If we were to go the route of having a config file I would strongly prefer to not have the need of any custom `Deserializer` logic and simply use macros to derive everything we need.

**Comment by nlordell** [comment]
> How would having a configuration file save us from having to implement custom parsing logic?

We could use macros. For example, something like:
```
#[derive(Deserialize)]
struct Config {
    cow_fee_factors: BTreeMap<f64, f64>,
}
```

Would allow us to write the following config file:
```toml
[cow_fee_factors]
"10.2" = 0.9
"100.0" = 0.75
"1000.0" = 0.5
```

**Comment by nlordell** [comment]
That being said, I think the format is simple enough that it is fine to implement and include for now.
