### ISSUE TITLE
Expose Solution Competition Externally

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#1741]
This _epic_ issue captures the work to make solver competition be visibly externally (and not just be private to the driver).

There are currently two approaches for tackling this:

### The Easy Way

The easiest, and least invasive approach, would be for the `driver` to have some blessed "api-key" and be allowed to store settlements in the orderbook.

This way, the driver could:
1. Collect all solutions from our current solvers
2. Perform local solver competition (so filters out the settlements that fail transactions)
3. Call `POST api/v1/solution_competition` with some "solution competition data" including the full auction (or an auction ID - but this would require storing the auctions some other way) as well as each "successfully simulating" solution, 

### The Hard Way

The harder and more invasive way to make this change would be to move settlement competition entirely to the orderbook API. In this model, the driver would submit settlements directly to the orderbook API and have it be responsible for verifying the settlements as well as determining the winner.

This is a more involved change as it would require:
- Closing auctions (i.e. building an auction and then recording it as "finalized" with some ID attached to it). The reason for this is to ensure multiple consecutive calls to `api/v1/auction` should return the same orders and prices! This is to allow things like driver-restarts mid auction, as well as multiple external drivers (decentralized future 😄 🤖).
- Have a way for settlements to "refer" to some existing auction at a database level (so you can query auction + settlements for ID `42` and get all orders that were included plus all settlements that were submitted and, if the auction is done, which one won and which one is on-chain)
- Either move settlement submission component into the `orderbook` or a separate `submitter` pod that queries the orderbook API for new settlements and just executes them on-chain as the driver does currently.

All in all, this is quite a bit more work but fits more nicely into our "decentralized future".

**Comment by vkgnosis** [comment]
Would it be useful to narrow down what the api should provide first before taking solutions into account? I feel like whether we want the api to have an auction id should be (mostly) decided up front. 

> Refactor settlement submission into a separate component. Once the winner is determined, then the settlement submitters need to compete to get the settlement transaction on-chain as fast as possible

This feels like a separate problem to me that we should tackle afterwards. We have our current submission code and we can run that in the orderbook, driver, separate pod pretty easily. One thought I do immediately have is that competition doesn't seem like the best fit for it because we can achieve better solutions by cooperating. E.g. if we agree that submission strategy 1 is better than 2 at this moment and 1 uses less gas then we decide to just do 1. With competition strategy 2 has no reason to yield. Also we'd have to define a bunch of rules around competition which seems hard and I'm not sure how much we gain by making this decentralized in this way.

**Comment by nlordell** [comment]
> E.g. if we agree that submission strategy 1 is better than 2 at this moment and 1 uses less gas then we decide to just do 1

The way I would see this is that the solvers would sign transactions with the gas price of submission strategy 1 (i.e. smaller tip) and then 2 would be less incentivized to participate.

You're right that this is likely a separate issue that we can leave until after though.

**Comment by MartinquaXD** [comment]
Both ideas make sense to me.
Do you think also storing settlements which didn't pass the simulation could be helpful for debugging issues in the future?

**Comment by nlordell** [comment]
> Do you think also storing settlements which didn't pass the simulation could be helpful for debugging issues in the future?

I would actually have the orderbook API reject such settlements. Also, if we "stream" the settlements from the driver to the solver (i.e. we send them as soon as they are ready) we can even see cool things like "live" settlement competition as well as reduce some node pressure that happens when all settlements get simulated at the same time.

One detail with doing ☝️ is that the state of the block change may change, so settlement simultations on `latest` may become invalid or become valid over the course of the settlement competition. With that in mind, I think it makes sense to accept settlements by simulating them on the "auction block" (currently the block on which we fetch liquidity) and then do the final competition right before deciding the winner?

I think simulating auctions on the "auction block" makes sense for other reasons as well, since it is a "special" block from the protocol perspective (for example, CIP-2 specifies that for solvers to use internal buffers they need to prove that there existed some on-chain liquidity at the the time of the auction - so on this "auction block").
