### ISSUE TITLE
Production - Staging coupling

### ISSUE THREAD

**Issue by e00E** [gnosis/gp-v2-services#25]
Now that orders are no longer stored on chain, separating production from staging will be more difficult. We want there to be a single source of truth of the orderbook for the benefit of the solver but then how can we test a staging environment?

While we are still iterating we run only on staging (and don't have to persist orders). Later the order format and core orderbook api should not change so running it only on production is fine.
If we wanted to add additional endpoints (like helpers for the frontend) we could do this by running another orderbook api on staging that internally forwards all the existing/unchanged endpoints to prod but implements a new api itself so that this could be tested with a staging version of the frontend.

I am not sure about the solver. For GP we have longer and fixed time span batches which allows us to have different target submission time offsets at which point we check that submitting the solution is still sensible (batch hasn't changed, solution improves objective value). For OBA there is probably not enough time to have a setup like this and we don't batches at fixed times that must be improved by another solution.

**Comment by fleupold** [comment]
For now we decided to create completely separate environments for staging and production.
