### ISSUE TITLE
Settlement workflow

### ISSUE THREAD

**Issue by e00E** [gnosis/gp-v2-services#26]
In GP we know exactly when we should start and stop solving. This is different in OBA where the timeline is more continuous. 

In OBA the token pairs are independent so we can restrict the analysis to one token pair. We will have new orders becoming valid at any time based on nonce and existing orders becoming invalid based on nonce and validTo. Orders could also become valid/invalid because the user's funds changed or their approvement of the contract spending the funds changed.

The settlement code look like this:
1. Get the current nonce and time from the smart contract.
2. Filter out orders that don't match.
3. Filter out orders that have insufficient funds or insufficient approvement.
4. Decide whether we should settle now or wait for more orders.

How often do we check 3? Probably not a problem for low number of orders but for large number could be too much stress on the node to check this too often. Could assume that this changes rarely so we don't need to check all the time.

How do we decide 4? The specification says orders should be settled after ~1 minute. So we need a timestamp of order creation and then settle if any valid order is older than 1 minute.

This depends also on how the frontend chooses the nonce of orders. I made a comment about this in the spec too. If the frontend chooses current_nonce + 1 then we could be in the situation where we have orders for the next nonce, but not the current so we should submit an empty settlement just to increase the nonce so we can submit a real settlement.

**Comment by fleupold** [comment]
We could schedule a runloop whenever an order comes in (with some delay) or attempt to match "every minute". The second option might make it more predictable for MM to know when to give us their quotes, but the other approach seems more flexible (e.g. to not give someone a very short batch when they are the first one to submit in a while but happen to do so at 13:37:55).

> This depends also on how the frontend chooses the nonce of orders.

I think the frontend should ask the backend for the correct nonce (giving us control). This can be used in case we have too many orders backlogged to schedule orders already for the next batch.

**Comment by fleupold** [comment]
This feels outdated/implemented for now.
