### ISSUE TITLE
Make a script to test real rinkeby deployment

### ISSUE THREAD

**Issue by vkgnosis** [gnosis/gp-v2-services#263]
I think it would be a good idea to have a script that can test the real deployment on xdai or rinkeby (where gas is cheap) by submitting orders for some erc20 token we control (so that we can mint) that should be settleable and then waiting a couple of minutes to see if the settlement happens. Kind of like an extended e2e test but with the real deployment. We could run that script on demand or for example nightly.

**Comment by fleupold** [comment]
Do you have an example for the type of bugs you'd expect to be found there? We had such a test in v1 but got rid of it because it took a long time and didn't give us good signal (some false alerts from time to time, when nodes where unavailable or the solver was out of test eth).

**Comment by vkgnosis** [comment]
I remember the v1 test was part of CI which was overkill. This one I don't want to run for every PR just manually or nightly. It would be useful until we naturally get more settlements to catch things like the demo not working.

**Comment by fleupold** [comment]
This has been implemented: https://github.com/gnosis/gp-v2-trading-bot
