### ISSUE TITLE
[explorer] Order details API

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-v2-services#268]
![UX_Explorer v1 4 - order detail page _ SELL order   FILL](https://user-images.githubusercontent.com/2352112/106740897-4bfdb380-661b-11eb-82e4-7fcdd2e0c9d0.png)

> This issue is to keep track of the issue raised by @alfetopito here https://gnosisinc.slack.com/archives/CC3C5SMB5/p1611271424004300 

The issue is created to agree on the API and behaviour for the order details page, which is a central point in the Explorer. Many users will arrive to the Explorer directly to this page, following a link from other UIs, CLIs, or bots.

The spec is not fully defined yet, but we have some nice wireframes. We'll be working on defining it better.
https://docs.google.com/document/d/179i8zuUrHpfvpU988HMqLB_isTJB383aOS9rGaJygh4/edit

It would be good to discuss all aspects of it, and be able to get an idea when this will work with expired and filled orders. Probably this is related to some other task regarding persistence.

**Comment by nlordell** [comment]
Order details should all be available AFAIK. Feel free to re-open if there is something missing.
