### ISSUE TITLE
Transaction nonces and submitter accounts

### ISSUE THREAD

**Issue by e00E** [gnosis/gp-v2-services#27]
In GP we have one address from which we submit solutions per solver. There we don't have to think about nonces much because batches are 5 minutes apart so the only thing to worry about was cancelling potentially cancelling the previous solution submission for example if the gas price wasn't high enough.

In OBA this is more complicated because we settle different token pairs independently. If we use the same account for all transactions then we need to make sure that we increment nonces properly and that transactions always go through (maybe because we manually cancel them). We could have a something like a transaction manager object that knows about all transactions we are currently trying to send and is able to adjust their gas prices or cancel them.

Or we could try having multiple submitter accounts so that they influence eachother less. We could for example cycle through 10 different accounts or have one account per token pair (which doesn't seem feasible because there are too many).

**Comment by nlordell** [comment]
Closing as I believe this issue is no longer relevant:
- We detect pending solution transactions and wait for them to be mined on startup.
- We merge multiple settlements into one, so we don't need multiple accounts atm.
