### ISSUE TITLE
Clarify postgres backups with devops

### ISSUE THREAD

**Issue by vkgnosis** [gnosis/gp-v2-services#270]
In the Monday meeting someone asked about how backups work with the database and I said the amazon hosted postgres creates them for us.
This is what I remembered from an early talk with dev ops but we should clarify what exactly the backup policy is and how hard it is to restore a database from earlier versions.

**Comment by fleupold** [comment]
Maybe this conversation should be held in slack rather than on github? (Might not hurt to document the outcome here, but we usually keep operational things private).

**Comment by vkgnosis** [comment]
Sure. Mainly wanted an issue as a task tracker. Can probably put the outcome in a Readme in the staging repo.

**Comment by fleupold** [comment]
It's automatically backed up weekly and we can increase the frequency if needed.
