### ISSUE TITLE
How do we want to handle database schema migrations

### ISSUE THREAD

**Issue by vkgnosis** [gnosis/gp-v2-services#295]
I am not sure what the best or standard way to do this is and how it would interact with high availability etc. Since we probably will have a migration eventually it would be good to plan this.

We probably would have migration postgres scripts and we could store a schema version in the db. But not sure if we would run those scripts automatically or manually or how to test them. For testing once we have a prod setup we could probably clone the database to staging and the test the migration and new code using the new schema there.

**Comment by fleupold** [comment]
I was thinking if for now we could run a "migration" script before our service starts up. This way, once we implement the "ready" route, a previous pod would not shut down until the migration and new version is ready to be used. This would however only work for backwards compatible upgrades.

For more complex upgrades, likely need to complementary copies of the data and some job to replicate new entries between schemas until it's fully deprecated (e.g. until staging reaches prod as you pointed out).

**Comment by vkgnosis** [comment]
Anxo linked us https://flywaydb.org/ (haven't looked into it yet).

**Comment by fleupold** [comment]
We started using flyway and so far it has been quite good.
