### ISSUE TITLE
[explorer] API order details + fills

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-v2-services#298]
We are working in the order detail page, which we think is a core part of the protocol. It's a page that shows you:
* Information regarding the any order (both open orders or historic orders)
* Includes the details: like price, and amounts
* Includes the state, and fill information
* Lastly includes information of the fills (trades)

![image](https://user-images.githubusercontent.com/2352112/107527333-03b13900-6bb9-11eb-97e9-51d1f4387dd8.png)

![image](https://user-images.githubusercontent.com/2352112/107527400-10359180-6bb9-11eb-8522-0fe3c22abf3a.png)

The order details page:
https://docs.google.com/presentation/d/10t4Hs3EAA3M99G_hPQxrtfZeWo6vJGsI/edit#slide=id.gb9d26145de_0_535

Specs + API definition
https://docs.google.com/document/d/179i8zuUrHpfvpU988HMqLB_isTJB383aOS9rGaJygh4/edit?ts=6022bf99#heading=h.b3h1m36ltz1k 

cc/ @nlordell @alfetopito @fleupold @e00E

**Comment by nlordell** [comment]
I believe this can be closed as all necessary information for a trade/order should be available. Feel free to re-open if I missed something.

**Comment by anxolin** [comment]
Cool! linking to our issue. We are delaying that one until we create limit order interfaces
