### ISSUE TITLE
[API] Exotic Trade Query Fiilters

### ISSUE THREAD

**Issue by bh2smith** [gnosis/gp-v2-services#311]
- token: Either sell or buy token. Allows to see trades with one token
- sellToken
- buyToken
- batchId: Trades included in a batch
- appId: Trades with a given appId
- fromDate
- toDate
- open: bool. Where
    - true gives trades for open orders. 
    - false: gives trades for orders that are EXPIRED, FILLED or CANCELED

**Comment by anxolin** [comment]
Awesome! We can make nice things with these!

**Comment by bh2smith** [comment]
When enriching the `TradeFilter` to include some of these exotic search parameters, it was proposed by @fleupold (in #316) to use the following pattern for `order_uid` and `owner` since we prohibit both from being specified in trade query:

```js
struct TradeFilter {
  from: DateTime<UTC>,
  to: DateTime<UTC>,
  inner: Option<Inner>
}

enum Inner{
  Owner(H160),
  OrderUid(OrderUid),
}
```

**Comment by fleupold** [comment]
The same is true for our OrderFilter (there we can also filter by user and UID) so if we changed it, it would probably make sense to change in both places.

**Comment by anxolin** [comment]
not sure i understand, but that `inner` thing sounds strange. I guess you tried to model is one filter or the other. U guys know best about Rust good patterns.

**Comment by fleupold** [comment]
Ben didn't copy my comment asking to pardon the poor/lazy naming. 

The point is that part of the "filter" is mutually exclusive (it doesn't make sense to filter on an orderID and a user), so a good way to harden our type to enforce this is by using an enum. 
However, there are some fields that are additive to the mutually exclusive fields (e.g. "from" & "to"). So to model this we need a struct which contains an "inner" enum.

**Comment by bh2smith** [comment]
The naming isn't quite settled yet, but the point is that only one of `owner` or `order_uid` can be specified since both wouldn't make sense, the "inner" is just an enum that is one or the other.

**Comment by anxolin** [comment]
It's nice rust allows to do that. I can see this getting messier if you really want to capture the logic. At the end you'll have to validate the somewhere, and there'll probably be logics like, the date range cannot be longer than 1 year. If they specify this filter, it necessarily need this other, ...
It was curiosity only, if it comes to that, it's easy to go to another model. 

The part I don't get now, is why the date is not optional? If I filter by orderId, I shouldn't need dates, right?

**Comment by bh2smith** [comment]
The dates will be optional. This is just a quick dirty example. We already have validations like this in place, but it will be nice to have as few validations as possible (for maintainability).

**Comment by bh2smith** [comment]
@alfetopito  - This might also be a good place to log trade filter requests!
