### ISSUE TITLE
Trade API

### ISSUE THREAD

**Issue by bh2smith** [gnosis/gp-v2-services#317]
Would like an API endpoint for querying trades from the database. This task can be split into three parts:

1. API Specification (#308)
2. Database Preparation (#316)
3. Exposing the API endpoint (#314)

- [ ] Include transaction hash in the trade table - #334

**Comment by anxolin** [comment]
Thanks for adding the hash in the TODO

If this comes from the comment https://github.com/gnosis/gp-v2-services/pull/308#discussion_r575327800 , I'd love that we consider to add the `executionTime` of the trade, and if possible the `batchId` and the `tradeFee`

Basically we would like to be able to work in this beauty: 
![image](https://user-images.githubusercontent.com/2352112/108241765-7b004300-714c-11eb-82d4-bfae602ec85b.png)

**Comment by bh2smith** [comment]
It is my impression that a nice clean `batchId`can be constructed as `blockNumber * 10^4 + transactionIndex` since there can be at most 595 (= 12.5M / 21K) transactions in a single block at the current block gas limit and this still allows for the gas limit to go as high as 21M. `executionTime` is the timestamp of the transaction and `tradeFee` should be computed by you on the fly as the difference of `sellAmount - sellAmountBeforeFees` (I am only willing to return two of three three values and we have concluded that what should be returned is the same as what is currently returned for the orders). I hope this is alright.

**Comment by nlordell** [comment]
I also see the `batchId` as something something like `blockNumber || something`. One thing to note that it is techincally possible to have two settlements in the same transaction. So for batch ID we should probably use `blockNumber || settlement_log_index` instead of `transaction_index`.

**Comment by bh2smith** [comment]
I like the settlement log index idea, but not the OR. Would still need to add them for uniqueness.

**Comment by anxolin** [comment]
> executionTime is the timestamp of the transaction

Yes, exactly. I mentioned because I didn't see it in the return data. But maybe I'm wrong. Basically very relevant if we return trade info to say the execution time. 

> tradeFee should be computed by you on the fly as the difference of sellAmount - sellAmountBeforeFees

Aha, ok, if `sellAmountBeforeFees` for trades too perfect.

> It is my impression that a nice clean batchIdcan be constructed as blockNumber * 10^4 + transactionIndex

I think that a public API should return the IDs abstracted away from its implementation (it should be opaque as Felix mentioned in the trade schema PRs). Otherwise, you add a dependency that is unnecessary, and also makes a less comprehensive API. If you for some reason have to change the ID generation at a later point. 


> Is batchID supposed to be the same as what you have as Fill ID there in your image? If so, then it looks like the txHash will suffice.

Batch ID and Fill Id are different. Fill Id would identify a single trade. Batch id would identify a single batch

**Comment by nlordell** [comment]
> but not the OR.

Hehe, `||` in that sense meant concatenate bytes not logical OR operator. I've seen this notation used quite a bit in the context of encoding bytes. For example: <https://eips.ethereum.org/EIPS/eip-712#specification>

**Comment by bh2smith** [comment]
This will be closed as the PR #314 fulfills the minimal criteria of this task. A new issue #334 will take care of the open TODOs.
