### ISSUE TITLE
Trade PK not unique!

### ISSUE THREAD

**Issue by bh2smith** [gnosis/gp-v2-services#318]
At the moment we have the following primary key for Trades table. However, every trade happening in the same batch would be included in the same block as part of the same transaction... Unless log index means something else? Any thoughts @vkgnosis 

PRIMARY KEY (block_number, log_index)

error returned from database: duplicate key value violates unique constraint "trades_pkey"

this is mostly because of:

```
pub async fn insert_events(&self, events: Vec<(EventIndex, Event)>) -> Result<()> {
```

Which I would guess should accept `(EventIndex, Vec<Events>)` Rather than a Vec of tuples.

There doesn't appear to be a unit test for `insert_events` that actually takes more than a single tuple.

**Comment by nlordell** [comment]
A `log_index` is the index of the log (AKA Solidity `event` in the block). There is only one possible event at a given `(block, log_index)` AFAIK.

**Comment by bh2smith** [comment]
Right, so we can't use this to uniquely specify `batchID`and will have to go with transaction hash instead.

**Comment by nlordell** [comment]
> Right, so we can't use this to uniquely specify batchIDand will have to go with transaction hash instead.

I don't understand this conclusion. I think you should be able to use `(block, log_index)` of a `Settlement` event in order to uniquely identify a batch since it is unique.

**Comment by bh2smith** [comment]
> I don't understand this conclusion. I think you should be able to use (block, log_index) of a Settlement event in order to uniquely identify a batch since it is unique.

I don't have the settlement event, I am working with the trade events which happen with different log indices in the same batch. Its all good, this is sorted. However, I would use `block_number, transaction_index` as a much more natural notion of `batchId`. In particular we can use `block_number * 10^4 + transaction_index` since (given the current gas limit) the most transactions that can fit into a block are `12.5M / /21K = 595`  and this definition would allow for the block gas limit to go all the way up to 21M without needing to be revisited.

**Comment by nlordell** [comment]
Note that just using a transaction has is not enough, since a single transaction can in theory contain multiple settlements.
