### ISSUE TITLE
Print errors to stderr

### ISSUE THREAD

**Issue by vkgnosis** [gnosis/gp-v2-services#330]
In Gpv1 we used stderr for log messages we wanted to show as alerts. In Gpv2 I decided to go with regex filtering but it turns out that our kubernetes set up cannot handle regexes for long messages properly. So we need to go back to stderr.

**Comment by fleupold** [comment]
Maybe we can hide this in our kubernetes container by wrapping the output of our rust process in some bash function that pipes to different streams based on a regex (https://stackoverflow.com/questions/18559869/how-to-split-a-stream-to-stdoutstderr-based-on-regular-expression-pattern)?

This way our main binary would still log in a more standard way.

**Comment by vkgnosis** [comment]
It is a little more complicated because we also have to consider the log separator because log messages can be multi line. Probably too complicated for a bash script but could be a python script or simple rust binary. Having that could be nice for other projects in the future too. On the other hand it's more work to set that up because the docker container will need to contain the extra binary and the pipe instead of just running the main binary.

**Comment by fleupold** [comment]
Could something like this work?

log_splitter.sh
```bash
#!/bin/bash

common="^[0-9]{4}\-[0-9]{2}\-[0-9]{2}T[0-9]{2}\:[0-9]{2}\:[0-9]{2}\.[0-9]{3}Z[ ]*"
std_err_re="$common ERROR"
std_out_re="$common (TRACE|DEBUG|INFO|WARN)"

stream="/dev/stdout"
IFS=''
while read line
do
    if [[ $line =~ $std_err_re ]]
    then stream="/dev/stderr"
    elif [[ $line =~ $std_out_re ]]
    then stream="/dev/stdout"
    fi
    echo $line >> $stream
done
```

`cargo run ... | log_splitter.sh`

**Comment by vkgnosis** [comment]
Nice, that does seem to work and isn't as complicated as I thought. Couple of changes I made locally:
* use `#!/bin/sh` for portability
* use `read -r` to prevent special handling of `\`

Last thing I am not sure about is whether when echoing the line we need something special like `"$line"` because of how shell scripts expand variables and strings. Will look that up.

**Comment by vkgnosis** [comment]
Today I tried to make this script work in the docker container on kubernetes. In our image we only have `sh` and not `bash` which revealed some issues related to the syntax of the regex and having to use `expr match` instead of `=~` to match against a regex. This took me way too long and I had to check the manual for unix regex syntax which is very different from what I am used to in more modern languages.
So I was wondering what others think about using python instead of (ba)sh. The disadvantage is that we have to install a package in the container before running the real binary. So instead of running just `orderbook` we would run `apk add python3 && orderbook | log-script.py`. On the other hand technically our image doesn't have to provide `sh` or `bash` either so it is only luck that we do have `sh`. The advantage of the python script is that IMO it is more readable, more maintainable and less error prone.

```python3
#!/bin/python3
from sys import stdin, stdout, stderr
import re

regex = re.compile("^\d+-\d+\-\d+T\d+:\d+\:\d+\.\d+Z\s+(?P<level>[A-Z]+)")

output = stdout
while True:
    line = stdin.readline()
    if len(line) == 0: break
    match = regex.match(line)
    if match != None:
        level = match.group("level")
        output = stderr if level == "ERROR" else stdout
    output.write(line)
```

**Comment by fleupold** [comment]
I'm fine installing python in the binary docker image. Another option might be to "compile" the python script into a binary using cython or implement this script in rust and create another binary in our build step (but I'm not sure it's worth the effort).
