### ISSUE TITLE
Transaction Hash in Trade Event

### ISSUE THREAD

**Issue by bh2smith** [gnosis/gp-v2-services#334]
For many reasons, it will be important to include transaction hash in the trades table. Also, in order to get a unique `batchId` we would like to store the `log_index` of the settlement event as well.

**Comment by fleupold** [comment]
Transaction hash makes total sense in the trade table. For the settlements, are you suggesting to also put them in the trades table or should those be normalized into their own table?

**Comment by bh2smith** [comment]
I hadn't yet thought about where exactly to put the settlement log index. All I know at this moment, it that this value should be stored somewhere at the time of the event. So it will be handled by the event manager which is currently updating the trade table and including block_number and log_index (of the trade). So, if we were to keep the current schema, it might go it in trade table, but now that you mention it, we could probably move a couple of these things into their own table. Perhaps we can have a Settlements (or Batches) Table that contain 

```
txHash | blockNumber | log_index (of settlement) | bachId (PK) |
```

Where `batchId = blockNumber * 10^4 + log_index` is the primary key that is also stored as a foreign key in the trades table.

**Comment by anxolin** [comment]
Awesome. I think the proposal of modeling the batch ID, is superior. This entity is very relevant in our protocol.

I feel this PR has some relation to https://github.com/gnosis/gp-v2-services/issues/311#issue-807783136 

My vote would be to do, in order of importance:
- 1. Start with a basic model for the Batch: whatever is easy to create: batchId (PK), txHash, blockNumber, logIndex, solverAddress (+ any data we might have already, if objectiveValue makes it more complicate, we can reiterate later)
- 2. Return batchId and txHash already with the trades
- 3. Endpoint to return batch info by Id
- 4. Get batches endpoint
- 5. Improvements on batch model. Include and missing fields. 

With 1-2 we can already do include the links in the explorer!

**Comment by anxolin** [comment]
Hei @bh2smith, just for having some expectations, do you think the txHash is something we can realistically have for the COW soft launch? I was thinking that it's very nice if we allow to see the physical tx in Etherscan

**Comment by bh2smith** [comment]
Yes, @anxolin i will aim to have this before the weeks end. Sorry I didn't see this till now.
