### ISSUE TITLE
Removing orders from the orderbook

### ISSUE THREAD

**Issue by e00E** [gnosis/gp-v2-services#36]
The orderbook has no reason to keep orders around forever. When it knows an order has become invalid because the of the nonce or validTo it can automatically delete the order (including some safety block confirmation interval). There is no need to delete orders *only* when the solver tells the orderbook to.
In fact we do not need a "delete order" route at all. It is enough to rely on the automatic order expiry. Orders are only valid for one batch and the solver knows which batch it is settling / has already settled. Manually sending orders to delete to the orderbook adds no functionality but is more brittle.

**Comment by fleupold** [comment]
Agree that this is not strictly needed. It could be a way to "optimistically" and cheaply allow users to signal order cancellation to our backend (although technically the payload is still valid). But this is definitely not a priority and arguably little value if the order cancellation is not enforced.

**Comment by fleupold** [comment]
For now keeping orders around is needed for the explorer.
