### ISSUE TITLE
Checking order validity

### ISSUE THREAD

**Issue by e00E** [gnosis/gp-v2-services#40]
For an order to be settleable the user must have enough balance and approved the contract for spending. This can change any time so we can never be sure that an order is valid before settling but we can still decide how often and in what way to check this.

One approach is to cache this information per user and token and update it in some intervals based by making more view function calls. Here we can batch those requests but eventually we hit some throughput limit of the node.

Another idea is to listen to erc20 events to create this information. This would make each individually query faster because we have the information locally. However getting the events is a lot of work similar to the event based orderbook but for every erc20 token we are interested in. It also assumes it is possible to recreate the balance of user based on events which might not be the case in some erc20 implementations. Or maybe events are not emitted at all and so on.

**Comment by fleupold** [comment]
Maybe we can start off by just explicitly checking the balance in fixed time intervals (or whenever there is a `new_block` event). If node throughput becomes a bottleneck we could have a more sophisticated cache invalidation strategy that is based on internal calls (or events).

**Comment by fleupold** [comment]
One service we should evaluate is https://www.blocknative.com/explorer They seem to allow monitoring wallets for any kind of interactions in the mempool

**Comment by e00E** [comment]
A related question is whether the orderbook service should check order validity or whether only the solver should. The orderbook service would still check `validTo` so it can clear orders eventually but it could skip all the blockchain related checks.
Having the check in the orderbook service would allow us to not have the check in the solver and could make running multiple solvers easier since they can just trust the orderbook.
On the other hand this puts more work into the orderbook service that it conceptually does not need to do and when/if there are other order sources we most likely would want to check in the solver anyway.

**Comment by fleupold** [comment]
I was also thinking about this. Eventually we want some solver independent (DAO governed) service to have consensus on the list of "valid" user orders as they might be protected by some envy freeness criterion. Therefore I slightly tend towards putting it in the orderbook service (not in the solver for that matter).

Another argument might be that clients are likely interested in querying an orderbook that is actually valid so the orderbook service might as well do that for all clients.

I'm also hoping that the filtering logic can be somewhat service agnostic (in that it operates on some `Orderbook` struct which is shared between the solver and API crate) and as such could be easily™️ moved around if need be.

**Comment by fleupold** [comment]
I was playing around with blockscout a bit and I think we should be able to use their [WS subscription](https://docs.blocknative.com/websocket) with a filter like this:

```
{"_join":"OR","terms":[{"contractCall.methodName":"approve"},{"netBalanceChanges":"undefined","_not":true}]}
```

to receive notifications about approval and balance changes of a given. That being said, I think we should also implement a pull based RPC mechanism that works without third party services. Also their rate limiting even on the paid tier might become an issue in case we have a lot of active accounts.

My suggestion would be to create a

```rust
trait BalanceFetching {
  // warm cache and setup updates in the background
  async fn register(&self, address: H160, token: H160) -> Result<()>;
  
  // Not async and non-blocking
  fn get_balance(&self, address: H160, token: H160) -> U265;
}
```

that is backed by a cache. The cache could be invalidated and refreshed using Batch RPC calls on every new block, or using block-native (RPC call needed for initial balances, everything else can be computed from the deltas on the payload).

For fill-or-kill orders we would check filter them out when the balance/allowance is less than the sell_amount. **I'm not sure what we should do for partial orders though.** We need their original limit price to recover the signature, but could add "available_balance" on the OrderMetadata struct.
