### ISSUE TITLE
[Naive Solver] Invalid Solution when pool reserves << excess amount

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-v2-services#421]
The issue was raised by this [alert](https://gnosisinc.slack.com/archives/CPZA1AGKY/p1616769723024400).

For the instance with a single [trade](https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0x3ebebb0e80b7fa47f7f371ed7b4acbfb153385ba2bf99e3ec877a2f4a978971204a66cbba0485d7b21af836f52b711401300fddb605ddeea), both the Naive as well as the BaselineSolver found a solution. The naive solver claimed a higher objective value and therefore tried to submit first. 

The settlement simulation failed because we were trying to send a much larger amount of the buyTokens to the trader than we received from uniswap. This is because the pool used only had very small reserves (~10e7 when we were trying to trade ~10e11). Therefore the direct pool is unusable and the solution found by the Baseline solver was eventually accepted.

The naive solver still found the invalid solution, because when verifying a solution candidate in the code (cf. `is_valid_solution`) we only check if the limit prices are satisfied, not if the amounts traded lead to token conservation.

I tried to make change (https://github.com/gnosis/gp-v2-services/compare/naive_solver_bug?expand=1) that adds token conservation to the checks, however, I'm running into rounding errors leading to marginally unconserved token balances.

I'm not sure at the moment how to proceed. One option would be to pass in a "buffer size" and allow token conservation to be violated within this buffer. Another option would be to adjust the amount computation in the smart contract to always take a bit more and pay out a bit less to the traders to avoid small negative balances in the contract.

cc @twalth3r and @marcovc as you guys have probably thought about rounding issues with regards to token conservation as well.

**Comment by nlordell** [comment]
> (~10**7 when we were trying to trade ~10**11).

It took me a qhile to see this was 1e7 and 1e11.

**Comment by nlordell** [comment]
> errors leading to marginally unconserved token balances.

Is strict token conservation a requirement? Couldn't we just check for a `>= 0` balance change in all tokens to the settlement contract (that is `forall tokens T, totalExecutedSellAmount[T] >= totalExecutedBuyAmount[T]`?

**Comment by fleupold** [comment]
Strict token conservation is not a requirement but even with inequalities I'm getting some failing test case (if I add +1 rounding on one side, the inequality sometimes start to fail on the other side).

I also looked at rounding the excess amount down by one unit of shortage token 

```rust
let mut rounded_excess = excess.clone();
rounded_excess.buy_volume += excess.reserve / shortage.reserve;
```

but the values can still be off by a small epsilon.

For now, the most prominent avenue has been to use Rationals when computing uniswap_out/uniswap_in and only convert into U256 at the very last moment. I will send a PR with that suggestion.

**Comment by marcovc** [comment]
Something I haven't understood from our discussion this morning: Isn't exactly to solve this problem what the balance buffers are for? Or are we trying to get away without buffers?

**Comment by fleupold** [comment]
We are not trying to get rid of buffers. The instance that is causing the issue we have a rounding error leading to an imbalance in the order of many magnitudes (more than any reasonable buffer). 
I therefore wanted to enforce token conservation in the algorithm but I'm struggling getting this to work (🐰 🕳️ of "off by 1 errors" in unit tests) unless we have knowledge of the size of the buffers (which is some plumbing logic I was trying to avoid) or some other reasonable guess by what epsilon or token conservation can be violated.
