### ISSUE TITLE
[Event Handler] What to do with Interaction and PreSignature Events

### ISSUE THREAD

**Issue by bh2smith** [gnosis/gp-v2-services#431]
Would love to get some feedback on the proposed approach described here (cc. @gnosis/gp-services and/or @gnosis/gp-contracts).

We have reserved a [place](http://github.com/gnosis/gp-v2-services/blob/a7cd0ed35f3bfa1954d8e943978da1784224f6f4/orderbook/src/event_updater.rs#L153-L155) in the services to handle all events emited by the contract. At this point, the database doesn't have a place to record the following two events:

1. **Interaction(address indexed target, uint256 value, bytes4 selector)**
Emitted by `Settlement.sol` contains contract `address` interacted with, `value` of the transaction and a `selector` which represents the method being called (I think). 
2. **PreSignature(address indexed owner, bytes orderUid, bool signed)**
Emitted by Signing.sol when an account either pre-signs an order or revokes an existing pre-signature.

For item 1, I would propose creating an `interactions` table which can be linked to `settlements` in the same way that trades are. This table would store the fields emitted along with necessary indexing values to uniquely link each interaction to a settlement. Furthermore, it could be beneficial to have an additional table `KnownContracts` containing `contract_address | contract_name` so that we could better visualize the interactions taking place.

For item 2. I am not sure what this could be beneficial for, but I am also not overly familiar with the purpose of pre-signatures at this moment.

**Comment by vkgnosis** [comment]
We don't have to handle all events. Depends on if we are going to make use of them somehow. The todo was meant as a reminder for that. Right now I don't see a use case for these two events. On the other hand it might be useful to already have historic records of these events in the db when we end up wanting them in the future.

**Comment by bh2smith** [comment]
In that case, it might make sense to just create corresponding tables and insert the values upon receiving these events.

**Comment by fleupold** [comment]
I agree that we should only implement the useful events (iirc we added the interactions event to the smart contract as a debugging tool when analyzing complex solution execution traces). I don't think we need to handle this event in the API (maybe at some future point in the solver to figure out which interaction might be causing troubles to execute).

If we don't handle an event there is probably no value in writing them to the DB yet. We can always do a retroactive sync over past events later.

**Comment by fleupold** [comment]
The PreSign even will likely be relevant when we want to support Gnosis Safe. While eventually the Safe should work based off EIP-1271 signature, it might still take some time before the Safe Web UI supports this standard (it's not yet on their Roadmap).

Until then, we will likely have the frontend post the order data via our endpoint and wait for the Safe itself to confirm the Order via a pre sign transaction. The order the backend receive will become tradable as soon as their is a PreSign event for the given UID.
