### ISSUE TITLE
Token-Deny List as runtime argument

### ISSUE THREAD

**Issue by bh2smith** [gnosis/gp-v2-services#450]
Some tokens behave badly and don't work with our infrastructure even though they might be tradable in AMM pools. Such tokens are currently blocking our services over extended periods of time while orders containing misbehaving tokens (as buy or sell token) are valid and being passed onto solvers. 

This issue proposes a token deny list which is passed into the services at runtime and will be handled in the following parts of the code
- OrderCreation -> Deny creation of orders containing denied tokens
- fee estimation -> Skip fee estimation for denied tokens
- Exclude orders containing denied tokens in the solvable_orders filter (so not to pass these orders onto the solver).

@fleupold - may be able to provide some additional context along token examples.

**Comment by fleupold** [comment]
https://dashboard.tenderly.co/gp-v2/staging/simulator/78e7b41b-4caa-4ca8-bab2-90d7d6766db1 is an example of a bad transaction. The token is [Rare Coin](https://blockscout.com/xdai/mainnet/address/0xCF740AC463098E442B31A5E88F4b359B30255616/transactions) which is unfortunately not verified, yet part of the default Honeyswap Token List (https://tokens.honeyswap.org/)
