### ISSUE TITLE
Allow buying ETH

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-v2-services#461]
The smart contract sets the buy token address to `0xeeee...eee` to indicate the user wants to buy the native token (ETH on mainnent, DAI on xDAI).

The solver currently doesn't support this magic number and treats it as a regular address (for which any trade will likely fail as we cannot find any uniswap base liquidity). This task captures adding support for it in both the API (for fee/amount estimations - for now it might be enough to just handle it as WETH and ignore the extra gas cost of unwrapping) as well as in the driver (adding an "unwrap" interaction to the execution).

[`LimitOrderSettlementHandling`](https://github.com/gnosis/oba-services/blob/7cbe3c376b08a2658287d26ed2dda002489c2509/solver/src/liquidity.rs#L38) already allows returning a list of interactions ` when settle is invoked (method to get the smart contract relevant trade information). We can add an interaction for unwrap in https://github.com/gnosis/oba-services/blob/7cbe3c376b08a2658287d26ed2dda002489c2509/solver/src/liquidity/offchain_orderbook.rs#L44

Currently the interactions just get appended to the settlement interaction list. This can cause issues with the execution plan if e.g. we try to unrwap before we have gotten the WETH from the trade (assuming there is not WETH buffer in the smart contract).

We could try to order interactions in a post processing step in the driver and put unrwap interactions at the end of the list ( + potentially combining them so we only invoke `WETH.unwrap` once in case multiple people trade in the same batch).

**Comment by nlordell** [comment]
> This can cause issues with the execution plan if e.g. we try to unrwap before we have gotten the WETH from the trade

I think if we just do all wrap/unwrap operations for payouts last (so they are executed right before bought amounts are transferred out) then there should never be a problem.

For wrap/unwrap operations within settlement interactions (like wrapping DAI to cDAI to take advantage of some arbitrage opportunity in a cDAI-WETH pool for example) this is quite a bit more complex and would likely require solver support.
