### ISSUE TITLE
`contract` crate rebuilds without modification

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#470]
This is a particularly annoying issue during development where the `contract` crate is rebuilding despite no changes to it.

**Comment by vkgnosis** [comment]
How do you observe this? For me if I do for example cargo check twice in a row it doesn't rebuild.

**Comment by nlordell** [comment]
@fedgiac and I observed this when changing any files in the workspace caused `contract` to rebuild (regardless of whether or not it was needed).

After further investigation, it appears related to the VScode formatting which is touching files that aren't being edited for some reason and causing the rebuild.
