### ISSUE TITLE
Rare v2 token not working for settlements

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#508]
Trades with this token cause settlements to fail: https://blockscout.com/poa/xdai/address/0x57e93BB58268dE818B42E3795c97BAD58aFCD3Fe/contracts.

This issue just captures the work to investigate why, although it is likely for the same reason there are issues with Rare v1.

**Comment by fleupold** [comment]
Difficult to say, as the code is not verified. On tenderly we see:

![image](https://user-images.githubusercontent.com/1200333/116096049-3b545b00-a6a9-11eb-9479-140c44386f9b.png)


Maybe some kind of transfer fee when using a relayer. On Honeyswap, I was able to manually swap to wxDAI
