### ISSUE TITLE
Naive solver off-by-one error.

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#524]
It looks like the equation used by the naive solver may suffer from rounding errors, that cause an "off-by-one" in certain cases. This leads to failed settlements for tokens that don't have any buffer in the settlement contract:

The computed input and output amounts from the tenderly link from https://logs.gnosis.io/app/kibana#/discover/doc/63bc0b10-5f93-11e9-bf17-fbe383fc7c9c/logstash-2021.04.27?id=4kE6FXkBDHKb0ncgiERY (Apr 27, 2021 @ 23:27:02.000)
```
"input":{
  "amountIn":"147240147441114393"
  "reserveIn":"490350406561504850302"
  "reserveOut":"334129741725736"
}
"output":{
  "amountOut":"99999999999"
}
```

In this log document, we see the batch call that does the `getReserves` call https://logs.gnosis.io/app/kibana#/discover/doc/63bc0b10-5f93-11e9-bf17-fbe383fc7c9c/logstash-2021.04.27?id=00E6FXkBDHKb0ncgiERY (Apr 27, 2021 @ 23:27:01.417):
```
  {"jsonrpc":"2.0","method":"eth_call","params":[{"data":"0x0902f1ac","to":"0x3d2d3c4446e8a82445418523b9b5b376765e55a8"},"latest"],"id":56931}
```

Matching it to the response from the log https://logs.gnosis.io/app/kibana#/discover/doc/63bc0b10-5f93-11e9-bf17-fbe383fc7c9c/logstash-2021.04.27?id=1EE6FXkBDHKb0ncgiERY (Apr 27, 2021 @ 23:27:01.519):
```
[id:56931]: "0x00000000000000000000000000000000000000000000000000012fe3a490802800000000000000000000000000000000000000000000001a94fa98c7a6de717e000000000000000000000000000000000000000000000000000000006088814b"
```

ABI decoding this:
```
> const ethers = require("ethers");
> ethers.utils.defaultAbiCoder.decode(["uint112","uint112","uint96"], "0x00000000000000000000000000000000000000000000000000012fe3a490802800000000000000000000000000000000000000000000001a94fa98c7a6de717e000000000000000000000000000000000000000000000000000000006088814b").map(x => x.toString())
[ '334129741725736', '490350406561504850302', '1619558731' ]
```

So, in this particular simulation, we see that the naive solver and the actual computed swap amounts differ despite having the same reserve values.

**Comment by fleupold** [comment]
Likely related to #427 

At the time I spoke with @marcovc about this and I think one assumption that is also present in the MIP solver is that there are sufficient buffers in each token (which means a settlement might not work the first time a token is ever traded). In this case however, shouldn't the baseline solver have found a solution?

**Comment by fleupold** [comment]
The fact that the baseline solver wasn't used could be related to 

https://github.com/gnosis/gp-v2-services/blob/73160b2e8a1cb806f46a2ec21c12993063ef602d/solver/src/baseline_solver.rs#L92-L95

not handling `None` correctly for buy orders (paths that return `None` will be "considered best"). This should be fixed as a side-effect of https://github.com/gnosis/gp-v2-services/pull/521

**Comment by nlordell** [comment]
Maybe we can fix the off-by-one for buy orders in the `NaiveSolver` as well?

**Comment by nlordell** [comment]
> I think one assumption that is also present in the MIP solver is that there are sufficient buffers in each token

I think this is a math error since the reserves given to the solver matched the reserves on-chain. This means we will always pay 1 from our buffer for buy orders this way right?

**Comment by fleupold** [comment]
> Could it be related to the get_amount_in computation:

Yes I would think it's coming from there. I elaborated a bit on it in #427 but adding +1 here can lead to a bunch of larger imbalances on the other side. Maybe we can add +1 to the final resulting numbers but keep the rationals for computing the other side as is.
