### ISSUE TITLE
Baseline solver sometimes not working for buy orders

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-v2-services#530]
If one of the path candidates (any route from sell token to buy token via the base tokens) doesn't have enough liquidity, the Baseline solver doesn't find a solution.

The reason is that

https://github.com/gnosis/gp-v2-services/blob/73160b2e8a1cb806f46a2ec21c12993063ef602d/solver/src/baseline_solver.rs#L92-L95

is not handling `None` correctly for buy orders (paths that return `None` will be minimal and thus "considered best"). This is already fixed as a side-effect of https://github.com/gnosis/gp-v2-services/pull/521

**Comment by bh2smith** [comment]
Closed by #532
