### ISSUE TITLE
Add support for additional 1Inch parameters

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#538]
> I recall that 1inch allows to specify best price or gas efficient as a quote parameter. I would imagine the default is best price and that is also what we would choose on the user's behalf here, but I am not seeing any place where this is passed through to the 1inch client.

_Originally posted by @bh2smith in https://github.com/gnosis/gp-v2-services/pull/520#discussion_r623796896_

Specifically, when inspecting the API calls in their UI, I noticed that depending on whether or not "maximum return" or "lowest gas cost" is selected, the API call will use a different number of "parts" (from what I understand from the documentation, by how much the swap can be split into sub-swaps)
- maximum return: 3 requests with: `mainRouteParts=3&parts=4`, `mainRouteParts=40&parts=100`, `mainRouteParts=20&parts=80`
- lowest gas cost: 2 request with: `mainRouteParts=1&parts=1` (which means the swap can't be split).

Currently the API just uses the default value (which is 20/20), but this should get added so that we can eventually adjust this.

Additionally, they also use a `deepLevel={0,1,2}` undocumented parameter that we should experiment with :smiling_imp:.

**Comment by MartinquaXD** [comment]
Latest 1Inch API supports all documented parameters: #1599
