### ISSUE TITLE
Mainnet Prod Restart not picking up failed transaction

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-v2-services#541]
Logs: https://logs.gnosis.io/goto/aa3a423f6bd96ec8338e5d3627b41276

The freshly restarted solver detected a pending transaction at 15:39:12. However, around the same time the transaction was actually [mined](https://etherscan.io/tx/0x58d37af3df85739ae9074b711b422f7431e7ba667777628c626ffcc07faf8e1a) (as failed).

The solver then still tried to resend a solution at the same nonce (which is invalid since a node cannot reuse that nonce). It eventually timed out (causing a 5 minute downtime). 

The submission logic should probably keep checking if the previously found pending solution gets mined at some point?

![image](https://user-images.githubusercontent.com/1200333/116720270-44606780-a9dc-11eb-898c-1635e798fb12.png)

**Comment by sunce86** [comment]
Closing this issue as this does not happen after the settlement submission refactor.
