### ISSUE TITLE
Follow up tasks for better settlement simulation error logging

### ISSUE THREAD

**Issue by vkgnosis** [gnosis/gp-v2-services#545]
From #539

* [x] Have a metric for settlements that succeed at earlier block but fail at current block.
* [ ] Use a fixed block for the liquidity fetcher to ensure pool blockchain information comes from the same block.

**Comment by fleupold** [comment]
Here is an example where a settlement simulation failed right before submission (12426718) AND for block 12426716 which was current when liquidity was fetched, but would have succeeded at an intermediate block (12426717) which is likely the block at which the liquidity was fetched.

Using a fixed block for the liquidity fetcher would have avoided this alert.

https://gnosisinc.slack.com/archives/CUD4MUCUF/p1620918277001000
