### ISSUE TITLE
[Price Estimation] Integrate Sushiswap

### ISSUE THREAD

**Issue by bh2smith** [gnosis/gp-v2-services#546]
Initially, I had thought that the changes could be envisioned as follows:

- the main `fetch` method for `PoolFetcher`: 
    `PoolFetcher` takes a list of `AmmPairProvider` (one Uniswap and one Sushiswap) and the fetch method returns still `Vec<Pool>` but then there could/would be multiple pools for the same `TokenPair`.
- `UniswapPriceEstimator`: 
    would be renamed to `UniswapLikePriceEstimator` and updated to handle the case where two pools for the same `TokenPair` exist. In particular the `best_execution` method which makes used of `PoolFetcher::fetch` will be adjusted to handle the case of pools with multiplicity.

However, by simply renaming `UniswapPriceEstimator` to `UniswapLikePriceEstimator`, we could just instantiate one of these for each pair provider (sushi and uni) then implement `PriceEstimating` for a new struct like `MultiPriceEstimator` which consists of multiple `UniswapLikePriceEstimators`. From here, we would implement the trait methods on the values returned by the individual estimates. This would be more robust for the future, when incorporating `PriceEstimating` for sources with different logic, this may be the way to go.

The problem with the apparently more clever option is that having the independent pool fetchers means that the routes for price estimate are sticly bound to be contained in a single platform. Meaning, if the best route uses one Uniswap and one sushiswap pool. this price estimate wouldn't be found. In order to truely provide the best price estimate, the pools need to be mixed so to get the best price of each pool along the route.

Looking for suggestions on the proposal @fleupold, @vkgnosis...

**Comment by fleupold** [comment]
Maybe we can rename `UniswapPriceEstimator` to `BaselinePriceEstimator` (following the pattern we did on the driver side). We could then replace the logic around the concrete `PoolFetcher`

https://github.com/gnosis/gp-v2-services/blob/ae3d2387cf0bc464cab38fdffb62b3f3263d7165/shared/src/price_estimate.rs#L245-L251

with a `BaselineLiquidityFetcher` or the like that exposes a `fetch` method that returns a `HashMap<TokenPair, Vec<Pool>>` and under the hood manages multiple liquidity sources (Balancer could be added too).
