### ISSUE TITLE
Do not require minimum uniswap out amount because we might have buffer in contract

### ISSUE THREAD

**Issue by e00E** [gnosis/gp-v2-services#56]
I think we don't want to fail if the uniswap price is slightly worse than what we would need in order to make an even trade. Therefore our min amount should actually be 0. 

If the AMM price is too bad (so that even a small buffer held in the settlement contract wouldn't be able to dampen it) the entire tx would fail when we try to pay out the bigger order's proceeds. 

I do see that this might potentially be very hard to debug and it might be nicer to fail the tx closer to where our shortage happens (especially when we start integrating many liquidity sources). With that in mind, maybe we actually want to keep this here and only use 0 when we encode the interaction into calldata? This way we can at least log the desired min amounts.

_Originally posted by @fleupold in https://github.com/gnosis/oba-services/pull/54#discussion_r533706826_

**Comment by fleupold** [comment]
This is somewhat implemented by #387 . I think it's still important to control the minimum amount as we might otherwise be sandwiched in a way that drains all potential buffer.
