### ISSUE TITLE
Implement Balancer weighted pools

### ISSUE THREAD

**Issue by fedgiac** [gnosis/gp-v2-services#586]
Introduce the concept of weighted pool, which is one of Balancer's liquidity sources we are going to tap from.
This task includes implementing `BaselineSolvable` for this type of pools. The equations describing how the liquidity sources beave are [here](https://balancer.fi/whitepaper.pdf#trading-formulas), while the contracts using these formulas are [here](https://github.com/balancer-labs/balancer-core-v2/blob/master/contracts/pools/weighted/WeightedPool.sol) and [here](https://github.com/balancer-labs/balancer-core-v2/blob/master/contracts/pools/weighted/WeightedMath.sol ).
Additionally, it may be necessary to implement the custom rational number implementation from the Balancer contracts.

**Comment by bh2smith** [comment]
In the event that this is not available at the time of Event handling implementation, I will likely include something like the following as a starting point

```rust
pub struct WeightedPool {
    pool_address: H160,
    tokens: Vec<H160>,
    pool_id: [u8; 32]
    // TODO - Include link to this task here
}
```
