### ISSUE TITLE
Integration with Balancer V2 Liquidity

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#589]
This issue captures an overarching epic to integrate Balancer V2 liquidity as a first class citizen. The goal of this integration is to:
- Use Balancer V2 in the baseline solver
- Include Balancer V2 liquidity in the price estimation

Both of which (to my understanding) currently only use Uniswap (or Honeyswap on xDAI) and SushiSwap liquidity.

The current plan is to introduce a new kind of liquidity to model weighted (and scaled) pools used by Balancer. While techincally, both Uniswap pools could be modeled as a wighted pool (with weight of 1, scale of 1 and only two tokens), there are enough differences in how the amounts get calculated (Balancer pools use fixed point numbers for example) and the fact that a separate Balancer specific components would be needed made it seem not really worth it (and not reduce code duplication in a meaningful way in the end).

The main "plan of attack" for this is to:
- [x] Implement a `WeightedPool: BaselineSolvable` type in the `shared` crate that the `baseline_solver` is aware of (#586)
- [x] Added a `WeightedProductOrder` liquidity type that can be passed into the various solvers
- [x] Create a component for fetching pool parameters and state (#603)
  -  [x] This can either be done by using the Graph (as done in the Balancer SOR implementation)
  -  [x] Or fetching pool data on-chain (although this may require manual event indexing - TBD @bh2smith)
- [x] Add initial support to the `BaselineSolver` by considering `WeightedPool`s in its path candidates and checking prices.
- [ ] Encode Balancer swap interactions
  - Multiple swaps in a single settlement can get squashed into a single `batchSwap`

Currently the baseline solver does not intend to implement all SOR feature (for example, we won't split orders into multiple paths - something that is quite doable with the Balancer `batchSwap` API).

Resources:
[1] [Balancer whitepaper](https://balancer.finance/whitepaper/)
[2] [Balancer `WeightedPool` contracts](https://github.com/balancer-labs/balancer-core-v2/tree/master/contracts/pools/weighted)
[3] [Balancer SOR (note specific branch)](https://github.com/balancer-labs/balancer-sor/tree/john/ui-337-sor-add-limits)

**Comment by bh2smith** [comment]
I believe this is has been completed with the exception of, possibly, the last item

- Encode Balancer swap interactions (Multiple swaps in a single settlement can get squashed into a single batchSwap)

Perhaps @nlordell can attach a known PR to this since we have definitely encoded swap interactions.

**Comment by nlordell** [comment]
Indeed the last point is still not addressed.

**Comment by nlordell** [comment]
Created a separate issue to just track that change: https://github.com/gnosis/gp-v2-services/issues/1492
