### ISSUE TITLE
Make settlement with liquidity internal buffers more likely

### ISSUE THREAD

**Issue by vkgnosis** [gnosis/gp-v2-services#591]
Noticed this when reading the code again. We will only do this if the whole final merged settlement can be done this way. But if only some part of the merged settlement can be done with internal buffers then the whole thing fails. If we looked at individual settlements before merging then we would suceed more often.

**Comment by fleupold** [comment]
Here is a pointer to the code that does the settlement merging: https://github.com/gnosis/oba-services/blob/73cbfa407827a1b5a2c5e81481f219c77cc9062a/solver/src/driver.rs#L185
