### ISSUE TITLE
Settlement transaction sending code

### ISSUE THREAD

**Issue by e00E** [gnosis/gp-v2-services#60]
Related to https://github.com/gnosis/oba-services/issues/27 .
We need a piece of code tracks pending transactions so we know which nonce to use next. For the MVP on rinkeby we probably don't need advanced gas price and resending logic.
This is different from gpv1 because now we might have multiple settlements in flight at the same time. Or for the MVP we could say that we will in fact always wait for the previous transaction to clear.

**Comment by fleupold** [comment]
> For the MVP on rinkeby we probably don't need advanced gas price and resending logic.

I would still like to include it (most of it is already factored out to reusable components). If we have a MVP working on rinkeby I woudn't be surprised if we were asked to also deploy it on mainnet for demonstrating purposes.
