### ISSUE TITLE
Add ttl to bad token detector cache entries

### ISSUE THREAD

**Issue by vkgnosis** [gnosis/gp-v2-services#615]
Would it make sense to have a ttl for cache entries? I imaging some tokens can change their state (e.g. getting paused or a fee becoming enabled) so maybe caching results for 7 days on prod before we restart is a bit long?

_Originally posted by @fleupold in https://github.com/gnosis/gp-v2-services/pull/610#discussion_r635052232_

**Comment by fleupold** [comment]
Cache expiry has been implemented
