### ISSUE TITLE
Verify order validity

### ISSUE THREAD

**Issue by e00E** [gnosis/gp-v2-services#62]
based on time, users balance and fund approval and check whether order hasn't been cancelled. For the MVP we could say that we just assume orders to be valid but this seems like basic enough functionality that we should have it.
Related to https://github.com/gnosis/oba-services/issues/40

**Comment by fleupold** [comment]
Given we will likely have more "validity" criteria later on (blacklisting, etc), it might be nice to factor this into a chained OrderbookFilter similar to [how we have it in dex-services](https://github.com/gnosis/dex-services/blob/71d1681a0cff32c22dbd9ea69eb200f69f9826c7/services-core/src/orderbook/filtered_orderbook.rs#L84-L87). Each filter can be responsible of checking one validity criterion.
