### ISSUE TITLE
Keep token quality cache warm

### ISSUE THREAD

**Issue by vkgnosis** [gnosis/gp-v2-services#638]
We might want to keep the token quality cache warm so that random requests that happen to come after the timeout don't have to wait longer.

For tokens that we have never seen before we can't do this but we could refresh all existing entries in the cache automatically or if we want to allow the cache to shrink maybe only base tokens or tokens that have been traded recently.

**Comment by nlordell** [comment]
This should be addressed by the recent cache block.
