### ISSUE TITLE
Break block_number_from_tx_hash into testable components

### ISSUE THREAD

**Issue by bh2smith** [gnosis/gp-v2-services#659]
When introduced as a helper method for #641, it was realized that block
```rust
async fn block_number_from_tx_hash(&self, hash: H256) -> Result<u64>;
```

was essentially untestable because it would require a mocked Web3 connection. 
So not to introduce even more unrelated code to the task at hand, this is logged as a simple task and flagged with a TODO in the code.

We want to break the above trait method into 3. Namely

```rust
async fn receipt_from_tx_hash(&self, hash: H256) -> Option<TransactionReceipt>;
async fn block_number_from_tx_hash(&self, hash: H256) -> Result<u64>;
fn block_number_from_receipt(&self, receipt: TransactionReceipt) -> Result<u64>;
```

where `receipt_from_tx_hash` can rely on the presumably tested Web3, `block_number_from_receipt` can be directly tested and `block_number_from_tx_hash` is merely a composition of the other two.

Doing this would also eliminate some of the ugly nested `if let` statements needed to unwrap the nested `Result<Option<Option<U64>>`

**Comment by nlordell** [comment]
The aforementioned code has been removed, making this PR no longer relevant.
