### ISSUE TITLE
Race Condition with node balancer when fetching liquidity

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-v2-services#731]
For the price estimator, we built a retry in the `RecentBlockCache` that tries up to 5 times in case the most recent block has not been seen by all nodes behind our node balancer.

For the solver, we don't use the background updating and therefore fail immediately if we try to fetch liquidity for a block that is too recent for some of the nodes. Cf.:

> ERROR (pod: dfusion-v2-solver-mainnet-6cf7c5b74c-df4ph):
2021-06-15T02:45:42.586Z ERROR solver::driver: single run errored: failed to get pool
Caused by:
   0: method 'getReserves():(uint112,uint112,uint32)' failure: web3 error: RPC error: Error { code: ServerError(-32000), message: "header not found", data: None }
   1: web3 error: RPC error: Error { code: ServerError(-32000), message: "header not found", data: None }

While this is not a huge deal (we will retry in a few seconds) it makes the on-call channel noisy and so a good solution might be to build another PoolFetching abstraction that just swallows this type of error and retries after 1 s (for up to 5 times). 

This logic could potentially be reused inside the `RecentBlockCache` to not share the same sleep logic.

**Comment by vkgnosis** [comment]
The retry functionality is also used for cache misses, not just for the updates. So all we have to do is make the retry count an argument for the driver and set it in the pool config.

**Comment by vkgnosis** [comment]
My previous comment was half wrong. We already have the same retry mechanism in the driver as in the order book and it is set to 5 retries by default. As I wrote, it is used for cache misses and not just auto updates.

**Comment by fleupold** [comment]
Ah, you are right, so this issue should actually be fixed with https://github.com/gnosis/gp-v2-services/pull/713. Before the `LiquidityCollector` was using a different pool fetcher which didn't have a cache/retry logic, but now it's reusing the same cache so it has retry built in.
