### ISSUE TITLE
Verify order signature

### ISSUE THREAD

**Issue by e00E** [gnosis/gp-v2-services#80]
The previous implementation was removed at some point and we don't yet have a new one.

Edit: Not technically required for the demo because the smart contract already verifies validity and we can assume all orders are valid. But would be nice to have in the orderbook so that we return an error to the frontend in case their signing code doesn't agree with our's.

**Comment by nlordell** [comment]
Note that there are two possible signing schemes that gets encoded in the `v` parameter.

**Comment by nlordell** [comment]
Note that there are two possible signing schemes that gets encoded in the `v` parameter.

https://github.com/gnosis/gp-v2-contracts/blob/f2941b6e5a367f3f147eab014feb45e58b8ee30e/src/contracts/libraries/GPv2Encoding.sol#L252-L276
