### ISSUE TITLE
[Paraswap] Handle "price changed" error

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-v2-services#802]
This would fix alerts like these:

> ERROR (pod: dfusion-v2-solver-mainnet-75875777c5-gzjq5):
2021-06-28T21:53:23.481Z ERROR solver::solver::single_order_solver: Inner solver error: TransactionBuilderQuery result parsing failed: {"error":"It seems like the rate has changed, please re-query the latest Price"}

The paraswap solver 1) queries a price estimate and 2) if the estimate satisfies the limit price requests a transaction object for this price. The ☝️ error is shown if the price moved between the two requests.

In this case we should probably just retry solving the order instead of bubbling this error up.

**Comment by bh2smith** [comment]
Given that we are also getting another parse error

```
solver::solver::single_order_solver: ParaSwap inner solver error: TransactionBuilderQuery result parsing failed: {"error":"ERROR_BUILDING_TRANSACTION"}
```

I might attempt to implement some kind of ParseError and match on those which we are capable of handling (such at the one you have here in the issue). Coming from other languages (i.e. those having try catch) I would intuitively think that we could approach this like


```rust
try {
    let result = response.parse_expected_object()
catch {
    let error = response.parse_error()
    match error {
       price_changed => return something that invokes a retry,
       error-building-transaction => throw error as before, but maybe also include the request JSON as well
    }
}

**Comment by vkgnosis** [comment]
A nice solution in this case is an untagge enum https://serde.rs/enum-representations.html#untagged . You would have the existing success variant and the error variant and serde will deserialize the one that matches the data.
