### ISSUE TITLE
Error reading HTTP solver solution when it contains Balancer pools.

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#837]
When encoding the settlement for HTTP solver solutions that contain Balancer pools, it produces an `Invalid AMM` error because it cannot match a weighted pool ID with the corresponding Balancer pool. I believe this is related to different `usize => WeightedPool` maps getting used for the encoding and decoding, one with offset IDs, and one without.

Attached are sample instance and solution files.
[00_instance_raw.txt](https://github.com/gnosis/gp-v2-services/files/6793745/00_instance_raw.txt)
[05_solution_int.txt](https://github.com/gnosis/gp-v2-services/files/6793746/05_solution_int.txt)

**Comment by bh2smith** [comment]
Your analysis makes perfect sense. We never account for the perturbed index upon receiving. May actually be a use case for actually using the currently unused context from what they send us back, but we should probably just take the shift of index into account.

**Comment by bh2smith** [comment]
In reality this integer indexed map is kinda ridiculous and we should really be using the pool address. We should check again with @twalth3r for a reminder on why we index these things by integer...

**Comment by marcovc** [comment]
The ids of the orders/amms are completely irrelevant to the solver side (any string will do). The driver is free to choose whatever it is more convenient.

**Comment by bh2smith** [comment]
> The ids of the orders/amms are completely irrelevant to the solver side (any string will do). The driver is free to choose whatever it is more convenient.

My only wonder was if this might have some effect on the visualization tooling.

**Comment by marcovc** [comment]
Good point, maybe let Tom answer then!

**Comment by twalth3r** [comment]
Yes, for the solver it doesn't make a difference what the ID is, and for the visualizations it should be fine too (or can easily be fixed if needed).

**Comment by bh2smith** [comment]
Cool, I may consider going with addresses here although this change might require some bigger changes since the pool addresses may actually have already been forgotten by the time the pools reach the HTTP solver modeling phase.
