### ISSUE TITLE
Baseline solver panicking with buy orders.

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#838]
It appears that the Baseline solver is still panicking with buy orders.

<details><summary>Stack trace:</summary>

```
thread 'main' panicked at 'Path was found, so amount must be calculateable', solver/src/solver/baseline_solver.rs:215:18:

   0: rust_begin_unwind

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5

   1: core::panicking::panic_fmt

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14

   2: core::option::expect_failed

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/option.rs:1241:5

   3: core::option::Option<T>::expect

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/option.rs:349:21

   4: solver::solver::baseline_solver::Solution::into_settlement

             at ./usr/src/oba-services/solver/src/solver/baseline_solver.rs:213:30

   5: solver::solver::baseline_solver::BaselineSolver::solve

             at ./usr/src/oba-services/solver/src/solver/baseline_solver.rs:142:23

   6: <solver::solver::baseline_solver::BaselineSolver as solver::solver::Solver>::solve::{{closure}}

             at ./usr/src/oba-services/solver/src/solver/baseline_solver.rs:35:12

   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19

   8: <core::pin::Pin<P> as core::future::future::Future>::poll

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/future.rs:120:9

   9: <tokio::time::timeout::Timeout<T> as core::future::future::Future>::poll

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/time/timeout.rs:149:33

  10: solver::driver::Driver::run_solvers::{{closure}}::{{closure}}::{{closure}}

             at ./usr/src/oba-services/solver/src/driver.rs:123:36

  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19

  12: <futures_util::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/maybe_done.rs:95:38

  13: <futures_util::future::join_all::JoinAll<F> as core::future::future::Future>::poll

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/join_all.rs:97:16

  14: solver::driver::Driver::run_solvers::{{closure}}

             at ./usr/src/oba-services/solver/src/driver.rs:118:9

  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19

  16: solver::driver::Driver::single_run::{{closure}}

             at ./usr/src/oba-services/solver/src/driver.rs:376:27

  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19

  18: solver::driver::Driver::run_forever::{{closure}}

             at ./usr/src/oba-services/solver/src/driver.rs:104:19

  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19

  20: solver::main::{{closure}}

             at ./usr/src/oba-services/solver/src/main.rs:363:5

  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19

  22: tokio::park::thread::CachedParkThread::block_on::{{closure}}

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/park/thread.rs:263:54

  23: tokio::coop::with_budget::{{closure}}

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/coop.rs:106:9

  24: std::thread::local::LocalKey<T>::try_with

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:376:16

  25: std::thread::local::LocalKey<T>::with

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:352:9

  26: tokio::coop::with_budget

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/coop.rs:99:5

  27: tokio::coop::budget

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/coop.rs:76:5

  28: tokio::park::thread::CachedParkThread::block_on

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/park/thread.rs:263:31

  29: tokio::runtime::enter::Enter::block_on

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/runtime/enter.rs:151:13

  30: tokio::runtime::thread_pool::ThreadPool::block_on

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/runtime/thread_pool/mod.rs:71:9

  31: tokio::runtime::Runtime::block_on

             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/runtime/mod.rs:452:43

  32: solver::main

             at ./usr/src/oba-services/solver/src/main.rs:363:5

  33: core::ops::function::FnOnce::call_once

             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
```

</details>

**Comment by nlordell** [comment]
Essentially what is happening is that the solver is computing a trading path for a **buy** order over a Balancer pool, but is failing to build a solution over that path. The reason is that weighted pool computations are not symmetrical for Balancer with respect to the maximum in/out amounts.

Specifically, if you take a 0.5/0.5 pool with balances 2.0 A and 0.25 B,
- Max input amount of token A is `2.0 * 0.3 = 0.6` A
- Given an input of 0.6 A the output is ~0.0577 B
- Max output amount of token B is `0.25 * 0.3 = 0.075` B
- Given an output of 0.075 B the input is ~0.857 A (> the maximum input amount of 0.6 A)

This unsymmetrical nature of Balancer pools is the source of this panic.

This means that for this specific order and pool, we were able to compute a valid `get_amount_in_given_out`, but not the reciprocal `get_amount_out_given_in` using the result from the previous call.

**Comment by fleupold** [comment]
This is some very unfortunate pool logic (why do they need to limit the amount of trading on a pool)? I wonder if our MIP solver respects [this constraint](https://github.com/balancer-labs/balancer-core-v2/blob/0412f74f60a6908dc5eba3e669b76ba7990f1a87/pkg/pool-weighted/contracts/WeightedMath.sol#L92) (cc @marcovc, @twalth3r).

We could work around this by building the path backwards for buy orders so that we invoke the same method as in our baseline calculation step. This would however require an extra flag on the execution and also be exposed on the MIP solver execution plan.

As a short term fix, we should probably just remove the panic and fail `into_settlement` in that case?

**Comment by twalth3r** [comment]
At the moment, the MIP solver of course doesn't know anything about this constraint (there's an [analogous version](https://github.com/balancer-labs/balancer-v2-monorepo/blob/0412f74f60a6908dc5eba3e669b76ba7990f1a87/pkg/pool-weighted/contracts/WeightedMath.sol#L127) for the out-amount by the way).

I guess it wouldn't be a problem to add these two to the MIP solver. We may not even need an update to the format since the constants are hardcoded in the Balancer contract and not specific to a pool.

**Comment by marcovc** [comment]
Do we also need to care about the 2 constants below, [here](https://github.com/balancer-labs/balancer-v2-monorepo/blob/0412f74f60a6908dc5eba3e669b76ba7990f1a87/pkg/pool-weighted/contracts/WeightedMath.sol#L35-L42)?

**Comment by marcovc** [comment]
Does it make sense to try to keep the amm format similar to orders, and make the computation in the driver and specify the constraint as "max_buy_amount" / "max_sell_amount" ?

**Comment by twalth3r** [comment]
Oh, the invariant-related constraints seem tricky for the MIP solver :roll_eyes: 

> Does it make sense to try to keep the amm format similar to orders, and make the computation in the driver and specify the constraint as "max_buy_amount" / "max_sell_amount" ?

Unfortunately, there's no `max_` in the order format, and just having a `{sell|buy}_amount` might be confusing, no? I think we could either hardcode these constants on the solver side, too, or maybe pass them with the same names as in the smart contract (wondering if we shouldn't better have gone with protocol names as AMM kinds then) :shrug:

**Comment by marcovc** [comment]
> Oh, the invariant-related constraints seem tricky for the MIP solver roll_eyes

Why is there both a _calcOutGivenIn and a _calcTokenInGivenExactBptOut. What does "Bpt" stand for?
 
We might just opened a [can of worms](https://github.com/balancer-labs/balancer-v2-monorepo/blob/0412f74f60a6908dc5eba3e669b76ba7990f1a87/pkg/pool-weighted/contracts/WeightedMath.sol#L237-L238) :) 

> (wondering if we shouldn't better have gone with protocol names as AMM kinds then)
I think we should!

**Comment by fleupold** [comment]
> What does "Bpt" stand for?

I believe "BalancerPoolToken" (the ERC20 representation of your pool share)

**Comment by nlordell** [comment]
> Does it make sense to try to keep the amm format similar to orders, and make the computation in the driver and specify the constraint as "max_buy_amount" / "max_sell_amount" ?

I would also be for passing something this in per AMM pool. In theory the Uniswap pools also have a maximum buy/sell amount because of their choice of reserve storage (96-bit integer).

**Comment by nlordell** [comment]
> _calcTokenOutGivenExactBptIn

I believe this is for computing token output amount when leaving the pool, not for trading.

**Comment by nlordell** [comment]
> As a short term fix, we should probably just remove the panic and fail into_settlement in that case?

**Comment by marcovc** [comment]
> I would also be for passing something this in per AMM pool. In theory the Uniswap pools also have a maximum buy/sell amount because of their choice of reserve storage (96-bit integer).

Tom has a point since an amm in the instance file does not have any direction associated with the possible n*(n-1) token directions. So it doesn't make much sense there to speak about buy/sell tokens (my suggestion was because I was somehow thinking about executed amms which do have a buy/sell token).

Therefore I'm now also inclined for renaming WeightedPool -> BalancerPool, which implicitly means we have to obey those constraints  (no strong opinion though).

**Comment by marcovc** [comment]
> I believe this is for computing token output amount when leaving the pool, not for trading.

Cool, I guess that means that required changes to mip solver are easy.

**Comment by nlordell** [comment]
> associated with the possible n*(n-1) token directions

Right, but I was under the impression that for Uniswap and Balancer at least, these max amounts are per token and not per token direction.

**Comment by nlordell** [comment]
So, one more suggestion that came up in the weekly planning was to, when computing input/output amounts, also do the inverse computation to make sure that the reciprocal is also possible. That is, for buy orders for example:
- Compute the input amount given an output amount with `let input_amount = get_amount_out(...)`.
- Make sure it is possible to compute an output amount given the input amount from the previous step: `if get_amount_in(input_amount, ...).is_none() { return }`.

**Comment by bh2smith** [comment]
This proposed approach has been implemented in the original branch with the failing test:

https://github.com/gnosis/gp-v2-services/pull/840
