### ISSUE TITLE
[Match Solver] ETH Unwrap happens with sell amount on buy order

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-v2-services#841]
For this order: https://gnosis-protocol.io/orders/0x7d71e36b822483a3ac2f19a457262a194ee46f2dff13332499af1f975f834e465fb8b9512684d451d4e585a1a0aabfb48a253c6760e8be11

See this simulation: https://dashboard.tenderly.co/gp-v2/staging/simulator/1ed3a7fa-e32a-4137-a18d-cc3b8f15f84f

It's failing because it's trying to unwrap the sell amount (~420 xSushi) to ETH which doesn't work since the contract only holds the buy amount of ~1.9 WETH

![image](https://user-images.githubusercontent.com/1200333/125194550-1d32db80-e252-11eb-8895-8e1183d99ee8.png)

The order cleared instead with the HTTP solver (https://logs.gnosis.io/goto/97ca9682a77631a91f78cb22bed0dd7a)

My hunch is that it's because [here](https://github.com/gnosis/oba-services/blob/2b3696a1285fdac072cc2becefe5970c6cfa9495/solver/src/solver/matcha_solver.rs#L125) we use the `sellAmount` as execution regardless of whether or not it's a buy order (in which case we should use the buyAmount.

**Comment by nlordell** [comment]
This should be fixed with https://github.com/gnosis/gp-v2-services/pull/821
