### ISSUE TITLE
ParaSwap error Suspected Rate Change

### ISSUE THREAD

**Issue by vkgnosis** [gnosis/gp-v2-services#877]
> solver::solver::single_order_solver: ParaSwap inner solver error: Suspected Rate Change - Please Retry!

We might want to handle these like the price changed errors and internally retry instead of erroring out completely.

**Comment by fleupold** [comment]
I think they are already handled (after the release today we should retry these errors)

https://github.com/gnosis/oba-services/blob/9b409b1d2de22fcaa63adf601c9dce61ddc51697/solver/src/solver/paraswap_solver/api.rs#L76-L78

**Comment by vkgnosis** [comment]
Oh that is the price change. For some reason I thought that one was different.
