### ISSUE TITLE
Smarter solving and settlement workflow

### ISSUE THREAD

**Issue by vkgnosis** [gnosis/gp-v2-services#879]
Currently we find settlements first and then wait for the transaction to be mined.
We can improve this by continuing to solve while waiting for the transaction continuing to treat all orders as valid as if there was no transaction. Every interval we are currently updating the gas price we would use the currently best available settlement. This works for both public mempool and archerdao. For the mempool we can only update on increased gas price but for archerdao we can always change the transaction.

**Comment by vkgnosis** [comment]
I have been playing around with this idea in code. There is a problem with the public mempool if we also support multiple solver addresses. In the case where the account that is supposed to submit the transaction changes we cannot update the existing transaction because for the public mempool an update means reusing the same nonce.

With only one account in the public mempool this works because the chain can only include one of the transactions of the same nonce.
With one or multiple accounts on archer this works because one of the settlement transactions getting included makes the others fail which prevents them from getting included.
With multiple accounts in the public mempool we would instead get mined failing transactions wasting gas.

Potential solutions:
1. Do not use multiple accounts. We are probably not going to do this because is solver accounts is something we explicitly decided to support.
2. Do not use multiple accounts for public mempool transactions but still for archer. 
3. Do not support the smarter settlement workflow for public mempool (only archer).

For 2 and 3 this comes down to whether we value multiple accounts or smarter settlement workflow more. I think we have a significant preference for archer and plan on using it most of the time (unless we discover new issues with it) so either way we should implement the workflow. If it turns out that the driver code can easily generalize to the old and new workflow then 2 is not a big detriment.

**Comment by vkgnosis** [comment]
Another idea:
Only support updating the ongoing settlement on public mempool if the submitter account is the same. Strict improvement over 3.

**Comment by josojo** [comment]
Cool! I like your thoughts! Yes, I think 3 could be the way to go.

One more thought: Once we implement firm quotes taking from market makers, we should not resolve all the time, but settle exactly this tx, as MM need some good guarantees to work with us.

But sure, for all settlements that are trading against AMMs, this makes a lot of sense.

**Comment by fleupold** [comment]
We could also send a "cancellation tx" (21000 gas) for the no longer desirable solution.

One worry I have with the smarter approach is how it would work once we move to a more decentralised solutions finding. There, I'd assume one solver gets the right to settle a batch (e.g. every 30s) and would then be required to cancel their transaction if it wasn't mined by the time the next auction ends?

I think a smarter strategy should also be implementable in the decentralised solver case.

**Comment by vkgnosis** [comment]
Agree that it might be worth it to figure out decentralized solving before working on this more.
