### ISSUE TITLE
Alternative for inflight trades

### ISSUE THREAD

**Issue by vkgnosis** [gnosis/gp-v2-services#882]
Currently we keep track of trades from a completed settlement transaction as inflight trades and exclude them from the next driver loop. We do this because we ran into issues where the driver saw the transaction as mined and thus went into the next loop while the order book did not see that block yet. It would then return these orders again which then fail to simulate on the driver.
Maybe another way to do this would be to return from the order book the block at which it last updated as part of the solvable_orders call. With that we can compare it in the driver and wait until we see that the order book has seen the block that had our settlement transaction.
This is related to https://github.com/gnosis/gp-v2-services/issues/879 because the inflight orders don't mesh well with it. But also not sure if this is needed yet.

**Comment by nlordell** [comment]
This has been fixed by having the orderbook API also supply its last indexed block when querying solvable orders.
