### ISSUE TITLE
[Contract Upgrade] Extend Orders Table

### ISSUE THREAD

**Issue by bh2smith** [gnosis/gp-v2-services#898]
Extend order table to include three new columns 

1. `contract_address/version` - 20 bytes, 
2. `balanceFrom` - int/enum (0, 1, 2), 
3. `balanceTo` - int/enum (0, 1, 2)

    where 
    0 = EOA balance
    1 = Balancer Vault internal
    2 = Balancer Vault external

**Note** - Should be introduced together with #899.

**Comment by bh2smith** [comment]
This can be achieved in two ways, with the second being less concise, but probably more appropriate:


### Option 1: Add non-null columns with default values. This would mean that we will forever have to ensure we don't accidentally insert without specifying these values explicitly (this would be especially important for the settlement version, since the default would be the old contract version.

```sql
CREATE TYPE FundLocation AS ENUM ('owner', 'vault_internal', 'vault_external');

ALTER TABLE orders
    ADD COLUMN settlement_version bytea NOT NULL default '0x3328f5f2cEcAF00a2443082B657CedEAf70bfAEf',
    ADD COLUMN balance_from FundLocation NOT NULL default 'self',
    ADD COLUMN balance_to FundLocation NOT NULL default 'self';
```

### Option 2: Add new columns with no constraints on null-ability, update the existing records with default values and set the columns to be non-null afterwards. Like so,

```
ALTER TABLE orders
    ADD COLUMN settlement_version bytea NOT NULL default '0x3328f5f2cEcAF00a2443082B657CedEAf70bfAEf',
    ADD COLUMN balance_from FundLocation NOT NULL default 'owner',
    ADD COLUMN balance_to FundLocation NOT NULL default 'owner';

UPDATE orders
SET settlement_version = '0x3328f5f2cEcAF00a2443082B657CedEAf70bfAEf',
    balance_from = 'owner',
    balance_to = 'owner'
WHERE settlement_version IS NULL;

ALTER TABLE orders
    ALTER COLUMN settlement_version SET NOT NULL,
    ALTER COLUMN balance_from SET NOT NULL,
    ALTER COLUMN balance_to SET NOT NULL;
```

### Option 3 (a mix of the two)

Do Option 2 for `settlement_version` and Option 1 for the other two columns (essentially making `owner`) the default value for balance to and from fields.

At this moment, since many collaborators are sleeping, I will pursue Option 2 and would be more than happy to adapt upon request.

**Comment by bh2smith** [comment]
As an additional note, in order to avoid redundancy in the database, I would also propose a new table `SettlementContract` which holds the contract_address and is linked to orders via an integer for version number.

```
SettlementVersion

Id | contract |
---------------
1  | 0x33...  |
2  | new_one  |
````

**Comment by fleupold** [comment]
Can you elaborate on how this avoids redundancy? Given the contract address is sure to be unique, how is an order table with a reference to the contract address more redundant than an order table with a reference to the settlement version ID?

I would argue it just makes querying more complicated as we always need to join with this extra table.

**Comment by nlordell** [comment]
> contract address more redundant

I think it is regarding the additional 20-byte long `bytea` for each order (instead of a FK). Personally, I'm not particularly worried about this, but I know very little about DB performance.

**Comment by bh2smith** [comment]
Contract address is a value that will be the same for essentially every record in the DB. This redundantly occurring value has 20 bytes while the FK here has only 1. 

Using the (redundant) contract address directly in the orders table will cost us ~1 Mb per 100 records while the integer only 0.1 Mb. This is a savings of almost 1 Gb per 100k orders (which our dB likely already contains).

**Comment by fleupold** [comment]
An int (as it is currently designed in the PR) is 4 bytes. 

> Using the (redundant) contract address directly in the orders table will cost us ~1 Mb per 100 records

I think this math is off by a factor of 1000 (16 bytes * 100 should be 1.6 kB). 

Also this kind of data compression is something that I think we could do at the postgres DB layer as well (E.g. postgres may internally decide to represent common addresses with a shorter encoding and have a separate lookup table). I wouldn't implement this kind of compression on our application layer.

**Comment by bh2smith** [comment]
Alright, so it seems we will go without the bonus table and put the contract address directly. I am totally fine with this, just didn't want to wake up in the morning with a bunch of questions about why I put a redundantly occurring value directly into a table that is being accessed frequently.

**Comment by taminomara** [comment]
> Note that we will never actually need to join these tables because nobody will actually care what the contract address is and just look at version number as a value.

After reading the discussion I don't have any strong opinion on this anymore =)

I see three ways to go here:

- we store contract addresses directly in the orders table,
- we store contract addresses in a separate table and reference it from the orders table,
- we don't store contract addresses in DB and use `enum version`.

I'm not sure we need to store contract address in DB, although @nlordell brought a good advantage for having a contract address in the database:

> One advantage of having the contract address directly in the DB is that it is implicitly included in the signature.

Will just need to make sure signature won't break for older records when we update them.

**Comment by nlordell** [comment]
I think there is an unanswered performance question: what is the performance impact of filtering orders on `settlement_contract` as a `bytea` vs as a FK (we can do it without a join by first searching and caching the `settlement_contract` PK and then using it to search forever after - in theory comparing an int is much faster than comparing 20 bytes, however, there may be some fancy Postgres DB layer magic that makes this insignificant).

Note that I think this is outside the scope of this PR, just wanted to mention it as something we should come back to if we start hitting DB performance issues (by far not our current bottleneck at the moment). In order to come up with a definitive answer on this, we would need proper benchmarking and metrics in place to evaluate the best approach.

**Comment by fleupold** [comment]
> in theory comparing an int is much faster than comparing 20 bytes, however, there may be some fancy Postgres DB layer magic that makes this insignificant

Correct me if I'm wrong, but isn't this what `CREATE INDEX` is for?

**Comment by bh2smith** [comment]
> Correct me if I'm wrong, but isn't this what `CREATE INDEX` is for?

Seems reasonable, maybe we should do this in #914.
