### ISSUE TITLE
[Contract Upgrade] Solver Arithmetic

### ISSUE THREAD

**Issue by bh2smith** [gnosis/gp-v2-services#904]
It was mentioned (cc @fedgiac) that there was a `math.floor` used in a place where `math.ceil` (or vice-versa) was used that should probably be considered when performing this migration. This may have something to do with arithmetic that was changed in the smart contract due to auditor's recommendation. 

TODO - This task needs some elaboration.

**Comment by nlordell** [comment]
Specifically, when computing the executed sell amounts, we round in favour of the user. This means that the executed buy amount may be 1 greater than what it is with the currently used contracts.

The only think I could think of where this would matter would be in the solution objective value computation. However, it looks like we use big rationals there, so it shouldn't be an issue.

I think its still worth keeping this issue open a little longer and going through the code to make sure there is no other place where this could matter.
