### ISSUE TITLE
Add support for Balancer "fast-path" swap settlements.

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#925]
The upgraded GPv2 contracts support a `swap` settlement where a single order is traded directly against Balancer.

As the Balancer SOR solver will be coming along soon, we should support these kinds of solutions so that the Balancer SOR solver has a gas advantage WRT the objective function.

This task would entail:
- Adding support for two different kinds of settlements to be returned by the solver
- Add code for ABI encoding this kind of settlement

**Comment by fleupold** [comment]
> Adding support for two different kinds of settlements to be returned by the solver

Alternatively, we could try to implement some post-processing logic that checks if a solution can be optimised (e.g. if it only contains balancer interactions it can be fast-pathed). Such a pipeline could also be used to combine multiple consecutive balancer swaps in a "not only balancer" solution?

**Comment by fleupold** [comment]
Related to #675
