### ISSUE TITLE
Enforce valid order signature at type level?

### ISSUE THREAD

**Issue by e00E** [gnosis/gp-v2-services#96]
https://github.com/gnosis/gp-v2-services/pull/93#discussion_r538619943

Felix:
> I'd slightly prefer if we used UserOrder::default and in there create a real signature that is valid. Creating an invalid order creation and then mutating it into something allows to create semantically invalid data (not so important for the tests but also alluding to my general preference of checking signature at order creation time).

**Comment by e00E** [comment]
This type was intended to implement the serialization format. I can see some merit in having a checked `CorrectlySignedOrder` but I don't think enforcing that for this type meshes well with the serialization aspect. The new type can enforce it's invariant but it would also end up being harder to use for it because we would have to disallow mutation because that would invalidate the signature which makes tests more annoying.

In practice, in our non test code we are never going to mutate orders anyway so we are unlikely to gain much from the new type as long as we check the signature in the one place it matters: before adding it to the orderbook.
In test code we might not care about having a valid signature (like in the solver tests) and forcing this invariant would make tests more annoying to write.

**Comment by fleupold** [comment]
> In practice, in our non test code we are never going to mutate orders anyway

This is why I think the type should not allow mutation (it's nice if this safety guarantee can be enforced by the compiler).

> forcing this invariant would make tests more annoying to write.

Where would we want to mutate orders in tests? I can imaging creating orders for tests as a use case (where we don't care about the signature), but we can have a builder function which computes the correct signature for the test data.
