### ISSUE TITLE
Add prometheus metrics for token fee estimates

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#962]
As we have been getting some complaints from users about fee prices, we should add a Prometheus metric of the fee responses tagged by token address.

cc @anxolin

**Comment by vkgnosis** [comment]
I don't think prometheus metric for all individual tokens is great because there are too many which creates a lot of data. We could instead have a metric for the last used gas price for any fee and/or log the exact fees per token.

**Comment by anxolin** [comment]
If u track just the gas price, maybe is enough, although u don't know for sure the fee u gave to the users, u can guess and is possible for some cases is enough. However, I see some value in having the actual response price. 

The gas prices you would record, will probably be also very similar to the gasPrice stats in other places, so while is better to have our own to have more certainty or detect abnormal situation, if it's just for investigating some user complaint would be very similar to using the stats. So my point is, if we add a metric, better make it closer to what the user sees. 

I think prometheus has also some policies where u can tell it to delete data. If it's too much datapoints, we can always find a policy that works. 

Also, if there's too many, an alternative might be using histograms/summaries?

**Comment by vkgnosis** [comment]
The problem is that it is not a good practice to use labels for open ended data sets. See https://prometheus.io/docs/practices/naming/ :
> CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.

Token ids are fairly open ended which is why I do not want a separate label for each of them. For debugging things users request it is enough to log the token id, fee and gas price every time we give out a fee.

**Comment by fleupold** [comment]
Maybe there is a way to convert the fee back into ETH or USD to get an estimate regardless of token? We could internally still log the prices per tokens and then inspect outliers in Kibana.
