### ISSUE TITLE
Failure to parse Match responses

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#963]
> ```
> ERROR solver::solver::single_order_solver: Matcha inner solver error: Matcha Response Error DeserializeError(Error("data did not match any variant of untagged enum RawResponse", line: 0, column: 0))
> ```

I imagine the JSON returned from the Match API doesn't quite match-a (haha - get it?) what is expected by the solver.

**Comment by fleupold** [comment]
We probably need to add an unknown error subtype lie we do in Paraswap (https://github.com/gnosis/oba-services/blob/73cbfa407827a1b5a2c5e81481f219c77cc9062a/solver/src/solver/paraswap_solver/api.rs#L124-L125)

**Comment by fleupold** [comment]
Actually #964 should close this.
