### ISSUE TITLE
Implement a "restart timeout" in the WebSocket GasNow estimator

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#965]
I noticed that the gas now estimator got stuck with:
> gas_estimation::priority: gas estimator 0 failed: last update more than 30 s in the past

And didn't seem to fix itself despite the service being up (was able to connect to it locally). I don't know if its an issue that it stopped receiving updates on our end, or if on the GasNow service's end, but we should probably restart the WebSocket connection if we stay too long without receiving any messages.

**Comment by vkgnosis** [comment]
This means that the connection itself was alive but it did not receive any updates. I agree that it should force reconnection in this case too.
