### ISSUE TITLE
Driver panics for orders tranding the same token.

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-v2-services#972]
The `solver` seems to panic if the orderbook contains orders that buy and sell the same token. While these orders shouldn't exist, it would be nice for the driver not to panic (but instead just alert that such an order was added).

**Comment by fleupold** [comment]
Related to #971, trading the same token could actually be used to do a gasless transfer.

**Comment by vkgnosis** [comment]
Do you remember where the panic was or on which day it happened? Am unable to find it in kibana. I think it might have been the naive or baseline solver but would be good to know which panic this issue is about. I'll still try to find it in the code anyway.
