### ISSUE TITLE
Logging Features

### ISSUE THREAD

**Issue by e00E** [gnosis/gp-v2-services#98]
1. [ ] create logging crate for shared setup between binaries
2. [ ] error log panics
3. [ ] log to stderr based on severity
4. [ ] combining multiline log messages into a single line

I don't think 4 is needed anymore but we need to make sure that the log separator matches the logs we emit.
For 3 I am wondering whether this is the correct approach and if we shouldn't stay on stdout but make sure that warn and error severity is properly detected. Iirc in v1-services we introduced this to detect errors for the docker-compose e2e tests but maybe there is a better solution.

**Comment by fleupold** [comment]
>  if we shouldn't stay on stdout but make sure that warn and error severity is properly detected

For kibana it was a practical way to sort logs by severity (otherwise it would have required a logging format dependent regex). Do you have a concrete concern with this approach? If I understand unix file descriptors correctly stderr is intended precisely for that purpose.

**Comment by e00E** [comment]
It's more that in traditional linux you often chain commands together. So the data should stay in stdout and any diagnostic information like "retrying connection to server" would go into stderr. For our purposes this is irrelevant so we can use whatever.
My feeling is that parsing the log string is a little more correct than using two streams which feels more like a workaround because we're changing our binary to get around limitations of the stagaing setup.
`log:"ERROR"` had the problem that it detected the word error anywhere in the message. I'll see if there is a fix for that.

**Comment by e00E** [comment]
This is all implemented except for logging to stderr. Instead of  doing that, I set up a better log filter in staging that makes sure the `ERROR` part is in the correct place after the timestamp. This prevents false positives if `ERROR` shows up some place else in the log message.
