### ISSUE TITLE
Investigate bad token

### ISSUE THREAD

**Issue by vkgnosis** [gnosis/gp-v2-services#980]
It looks like EthPad is causing issues in simulation (https://dashboard.tenderly.co/gp-v2/staging/simulator/754fd516-3e5e-456b-9aeb-8e80c3813b81) but is not classified as a BadToken.
Order: https://gnosis-protocol.io/orders/0x861df8015564d4c96e191316b47849124350919b7a7120f66368e3cdd8f3d212788356e5d2abb4646d253eb02973f08c0b06d444611b6594

Should investigate what is going wrong and whether we can detect it.

**Comment by vkgnosis** [comment]
The code for the contract is https://etherscan.io/address/0x9ed27d7f260ee52668b209a15159045011c8d007#code .

As Nick said on Slack:
> If the recipient is a pair and it isn't excluded, then it takes some fees on transfer. As such, the GPv2Settlement -> UniPair  transfer if taking a fee. But the bad token detector checks if some account -> GPv2Sttelement transfer is OK. (correct me if I'm wrong).

We test the transfer from the pool to the settlement contract and from the settlement contract to an address that doesn't own the token. The token takes fee on transfer to some addresses (not excluded pools) which we don't detect. This is something we in general cannot detect as their is no guarantee what pool address we pick in the detector.

**Comment by fleupold** [comment]
Makes sense.

While there is no guarantee, if we implemented #858 there would be a good chance that the simulated baseline path would be the same as the final solution (at least it means there exists a valid path - removing bad pools based on simulation failure is another pandora box).
