### ISSUE TITLE
[Untradable Token] Fraction

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-v2-services#983]
The [Fraction token](https://blockscout.com/xdai/mainnet/tokens/0x2bF2ba13735160624a0fEaE98f6aC8F70885eA61/token-transfers) is not tradable on CowSwap, because no pool with enough liquidity exists.

The largest pool is [this](https://info.honeyswap.org/#/pair/0x53704af4ff9031ebd461cb498ca717a4b6bca95c) Honeyswap pool with 0.1 Fraction balance .

Our bad token detector tries however to transfer one unit of the token. The issue is that Fraction by design only has a total supply of 1. Therefore finding a pool with 1 unit balance is never going to happen.

Is there any reason for this magic number? Would we be able to reduce the amount we try to ransfer?

**Comment by vkgnosis** [comment]
We transfer one base unit (based on token's decmials). This was arbitrarily chosen based on the expectation that a base unit is a lowish value. We can change that but not sure what value we should use.

**Comment by nlordell** [comment]
We can just send the full balance?
